// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_service_account_token

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServiceAccountTokenResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_token": schema.StringAttribute{
				Computed:            true,
				Sensitive:           true,
				Description:         "The token credential, and the secret that authenticates as this service account. Returned only by this operation and never retrievable again, so store it somewhere safe on receipt; an empty string on a dry-run create. Treat it like a password.",
				MarkdownDescription: "The token credential, and the secret that authenticates as this service account. Returned only by this operation and never retrievable again, so store it somewhere safe on receipt; an empty string on a dry-run create. Treat it like a password.",
			},
			"create_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the token was created. `null` only on a dry-run create.",
				MarkdownDescription: "When the token was created. `null` only on a dry-run create.",
			},
			"customer_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the customer whose service account the token belongs to.",
				MarkdownDescription: "ID of the customer whose service account the token belongs to.",
			},
			"expires_time": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "When the token should stop authenticating. Omit to let the server set the default expiry.",
				MarkdownDescription: "When the token should stop authenticating. Omit to let the server set the default expiry.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "API token ID. `null` only on a dry-run create.",
				MarkdownDescription: "API token ID. `null` only on a dry-run create.",
			},
			"last_used_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the token last authenticated a request. `null` until it is first used.",
				MarkdownDescription: "When the token last authenticated a request. `null` until it is first used.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Name, unique among the service account's tokens. Leading or trailing whitespace returns `400`.",
				MarkdownDescription: "Name, unique among the service account's tokens. Leading or trailing whitespace returns `400`.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 100),
				},
			},
			"service_account_id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the service account that owns the token.",
				MarkdownDescription: "ID of the service account that owns the token.",
			},
			"state": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "`active` to enable the token, `disabled` to stop it authenticating. Any other value, `deleted` and `expired` included, returns `400`. Re-enabling a token whose expiry has passed returns `422`.\nPossible values: `active`, `disabled`",
				MarkdownDescription: "`active` to enable the token, `disabled` to stop it authenticating. Any other value, `deleted` and `expired` included, returns `400`. Re-enabling a token whose expiry has passed returns `422`.\nPossible values: `active`, `disabled`",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"active",
						"disabled",
					),
				},
			},
		},
		Description:         "Manage non-human identities whose API tokens call the DoiT API with a fixed set of permissions.",
		MarkdownDescription: "Manage non-human identities whose API tokens call the DoiT API with a fixed set of permissions.",
	}
}

type ServiceAccountTokenModel struct {
	AccessToken      types.String `tfsdk:"access_token"`
	CreateTime       types.String `tfsdk:"create_time"`
	CustomerId       types.String `tfsdk:"customer_id"`
	ExpiresTime      types.String `tfsdk:"expires_time"`
	Id               types.String `tfsdk:"id"`
	LastUsedTime     types.String `tfsdk:"last_used_time"`
	Name             types.String `tfsdk:"name"`
	ServiceAccountId types.String `tfsdk:"service_account_id"`
	State            types.String `tfsdk:"state"`
}
