// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_commitment

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func CommitmentDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cloud_provider": schema.StringAttribute{
				Computed:            true,
				Description:         "The cloud provider associated with the commitment.",
				MarkdownDescription: "The cloud provider associated with the commitment.",
			},
			"create_time": schema.Int64Attribute{
				Computed:            true,
				Description:         "The creation time in milliseconds since epoch.",
				MarkdownDescription: "The creation time in milliseconds since epoch.",
			},
			"currency": schema.StringAttribute{
				Computed:            true,
				Description:         "The currency of the commitment (e.g., USD).",
				MarkdownDescription: "The currency of the commitment (e.g., USD).",
			},
			"end_date": schema.StringAttribute{
				Computed:            true,
				Description:         "The end date of the commitment.",
				MarkdownDescription: "The end date of the commitment.",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Commitment ID",
				MarkdownDescription: "Commitment ID",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the commitment.",
				MarkdownDescription: "The name of the commitment.",
			},
			"periods": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"commitment_value": schema.Float64Attribute{
							Computed:            true,
							Description:         "The commitment value for this period.",
							MarkdownDescription: "The commitment value for this period.",
						},
						"end_date": schema.StringAttribute{
							Computed:            true,
							Description:         "The end date of the period.",
							MarkdownDescription: "The end date of the period.",
						},
						"forecast_value": schema.Float64Attribute{
							Computed:            true,
							Description:         "The projected spend at the end of this period, based on a linear regression over the period's total spend series. 0 when insufficient history is available to compute a forecast.",
							MarkdownDescription: "The projected spend at the end of this period, based on a linear regression over the period's total spend series. 0 when insufficient history is available to compute a forecast.",
						},
						"marketplace_limit_amount": schema.Float64Attribute{
							Computed:            true,
							Description:         "The marketplace limit in absolute currency for this period, derived as commitmentValue * marketplaceLimitPercentage / 100.",
							MarkdownDescription: "The marketplace limit in absolute currency for this period, derived as commitmentValue * marketplaceLimitPercentage / 100.",
						},
						"marketplace_limit_percentage": schema.Float64Attribute{
							Computed:            true,
							Description:         "The marketplace limit as a percentage (0-100).",
							MarkdownDescription: "The marketplace limit as a percentage (0-100).",
						},
						"marketplace_spend": schema.Float64Attribute{
							Computed:            true,
							Description:         "The marketplace spend within this period.",
							MarkdownDescription: "The marketplace spend within this period.",
						},
						"start_date": schema.StringAttribute{
							Computed:            true,
							Description:         "The start date of the period.",
							MarkdownDescription: "The start date of the period.",
						},
					},
					CustomType: PeriodsType{
						ObjectType: types.ObjectType{
							AttrTypes: PeriodsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "The list of commitment periods.",
				MarkdownDescription: "The list of commitment periods.",
			},
			"start_date": schema.StringAttribute{
				Computed:            true,
				Description:         "The start date of the commitment.",
				MarkdownDescription: "The start date of the commitment.",
			},
			"total_commitment_value": schema.Float64Attribute{
				Computed:            true,
				Description:         "The total value of the commitment across all periods.",
				MarkdownDescription: "The total value of the commitment across all periods.",
			},
			"total_current_attainment": schema.Float64Attribute{
				Computed:            true,
				Description:         "The total current spend attainment across all periods.",
				MarkdownDescription: "The total current spend attainment across all periods.",
			},
			"total_forecast_value": schema.Float64Attribute{
				Computed:            true,
				Description:         "The total projected spend at the end of the commitment, summed across all periods. 0 when insufficient history is available to compute a forecast.",
				MarkdownDescription: "The total projected spend at the end of the commitment, summed across all periods. 0 when insufficient history is available to compute a forecast.",
			},
			"total_marketplace_spend": schema.Float64Attribute{
				Computed:            true,
				Description:         "The total marketplace spend across all periods.",
				MarkdownDescription: "The total marketplace spend across all periods.",
			},
			"update_time": schema.Int64Attribute{
				Computed:            true,
				Description:         "The last update time in milliseconds since epoch.",
				MarkdownDescription: "The last update time in milliseconds since epoch.",
			},
		},
		Description:         "View and manage commitment contracts with DoiT.",
		MarkdownDescription: "View and manage commitment contracts with DoiT.",
	}
}

type CommitmentModel struct {
	CloudProvider          types.String  `tfsdk:"cloud_provider"`
	CreateTime             types.Int64   `tfsdk:"create_time"`
	Currency               types.String  `tfsdk:"currency"`
	EndDate                types.String  `tfsdk:"end_date"`
	Id                     types.String  `tfsdk:"id"`
	Name                   types.String  `tfsdk:"name"`
	Periods                types.List    `tfsdk:"periods"`
	StartDate              types.String  `tfsdk:"start_date"`
	TotalCommitmentValue   types.Float64 `tfsdk:"total_commitment_value"`
	TotalCurrentAttainment types.Float64 `tfsdk:"total_current_attainment"`
	TotalForecastValue     types.Float64 `tfsdk:"total_forecast_value"`
	TotalMarketplaceSpend  types.Float64 `tfsdk:"total_marketplace_spend"`
	UpdateTime             types.Int64   `tfsdk:"update_time"`
}

var _ basetypes.ObjectTypable = PeriodsType{}

type PeriodsType struct {
	basetypes.ObjectType
}

func (t PeriodsType) Equal(o attr.Type) bool {
	other, ok := o.(PeriodsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PeriodsType) String() string {
	return "PeriodsType"
}

func (t PeriodsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewPeriodsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewPeriodsValueUnknown(), diags
	}

	attributes := in.Attributes()

	commitmentValueAttribute, ok := attributes["commitment_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_value is missing from object`)

		return nil, diags
	}

	commitmentValueVal, ok := commitmentValueAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_value expected to be basetypes.Float64Value, was: %T`, commitmentValueAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return nil, diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	forecastValueAttribute, ok := attributes["forecast_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`forecast_value is missing from object`)

		return nil, diags
	}

	forecastValueVal, ok := forecastValueAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`forecast_value expected to be basetypes.Float64Value, was: %T`, forecastValueAttribute))
	}

	marketplaceLimitAmountAttribute, ok := attributes["marketplace_limit_amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`marketplace_limit_amount is missing from object`)

		return nil, diags
	}

	marketplaceLimitAmountVal, ok := marketplaceLimitAmountAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`marketplace_limit_amount expected to be basetypes.Float64Value, was: %T`, marketplaceLimitAmountAttribute))
	}

	marketplaceLimitPercentageAttribute, ok := attributes["marketplace_limit_percentage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`marketplace_limit_percentage is missing from object`)

		return nil, diags
	}

	marketplaceLimitPercentageVal, ok := marketplaceLimitPercentageAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`marketplace_limit_percentage expected to be basetypes.Float64Value, was: %T`, marketplaceLimitPercentageAttribute))
	}

	marketplaceSpendAttribute, ok := attributes["marketplace_spend"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`marketplace_spend is missing from object`)

		return nil, diags
	}

	marketplaceSpendVal, ok := marketplaceSpendAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`marketplace_spend expected to be basetypes.Float64Value, was: %T`, marketplaceSpendAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return nil, diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PeriodsValue{
		CommitmentValue:            commitmentValueVal,
		EndDate:                    endDateVal,
		ForecastValue:              forecastValueVal,
		MarketplaceLimitAmount:     marketplaceLimitAmountVal,
		MarketplaceLimitPercentage: marketplaceLimitPercentageVal,
		MarketplaceSpend:           marketplaceSpendVal,
		StartDate:                  startDateVal,
		state:                      attr.ValueStateKnown,
	}, diags
}

func NewPeriodsValueNull() PeriodsValue {
	return PeriodsValue{
		state: attr.ValueStateNull,
	}
}

func NewPeriodsValueUnknown() PeriodsValue {
	return PeriodsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPeriodsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PeriodsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PeriodsValue Attribute Value",
				"While creating a PeriodsValue value, a missing attribute value was detected. "+
					"A PeriodsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PeriodsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PeriodsValue Attribute Type",
				"While creating a PeriodsValue value, an invalid attribute value was detected. "+
					"A PeriodsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PeriodsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PeriodsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PeriodsValue Attribute Value",
				"While creating a PeriodsValue value, an extra attribute value was detected. "+
					"A PeriodsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PeriodsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPeriodsValueUnknown(), diags
	}

	commitmentValueAttribute, ok := attributes["commitment_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_value is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	commitmentValueVal, ok := commitmentValueAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_value expected to be basetypes.Float64Value, was: %T`, commitmentValueAttribute))
	}

	endDateAttribute, ok := attributes["end_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_date is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	endDateVal, ok := endDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_date expected to be basetypes.StringValue, was: %T`, endDateAttribute))
	}

	forecastValueAttribute, ok := attributes["forecast_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`forecast_value is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	forecastValueVal, ok := forecastValueAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`forecast_value expected to be basetypes.Float64Value, was: %T`, forecastValueAttribute))
	}

	marketplaceLimitAmountAttribute, ok := attributes["marketplace_limit_amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`marketplace_limit_amount is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	marketplaceLimitAmountVal, ok := marketplaceLimitAmountAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`marketplace_limit_amount expected to be basetypes.Float64Value, was: %T`, marketplaceLimitAmountAttribute))
	}

	marketplaceLimitPercentageAttribute, ok := attributes["marketplace_limit_percentage"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`marketplace_limit_percentage is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	marketplaceLimitPercentageVal, ok := marketplaceLimitPercentageAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`marketplace_limit_percentage expected to be basetypes.Float64Value, was: %T`, marketplaceLimitPercentageAttribute))
	}

	marketplaceSpendAttribute, ok := attributes["marketplace_spend"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`marketplace_spend is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	marketplaceSpendVal, ok := marketplaceSpendAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`marketplace_spend expected to be basetypes.Float64Value, was: %T`, marketplaceSpendAttribute))
	}

	startDateAttribute, ok := attributes["start_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_date is missing from object`)

		return NewPeriodsValueUnknown(), diags
	}

	startDateVal, ok := startDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_date expected to be basetypes.StringValue, was: %T`, startDateAttribute))
	}

	if diags.HasError() {
		return NewPeriodsValueUnknown(), diags
	}

	return PeriodsValue{
		CommitmentValue:            commitmentValueVal,
		EndDate:                    endDateVal,
		ForecastValue:              forecastValueVal,
		MarketplaceLimitAmount:     marketplaceLimitAmountVal,
		MarketplaceLimitPercentage: marketplaceLimitPercentageVal,
		MarketplaceSpend:           marketplaceSpendVal,
		StartDate:                  startDateVal,
		state:                      attr.ValueStateKnown,
	}, diags
}

func NewPeriodsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PeriodsValue {
	object, diags := NewPeriodsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPeriodsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PeriodsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPeriodsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPeriodsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPeriodsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPeriodsValueMust(PeriodsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PeriodsType) ValueType(ctx context.Context) attr.Value {
	return PeriodsValue{}
}

var _ basetypes.ObjectValuable = PeriodsValue{}

type PeriodsValue struct {
	CommitmentValue            basetypes.Float64Value `tfsdk:"commitment_value"`
	EndDate                    basetypes.StringValue  `tfsdk:"end_date"`
	ForecastValue              basetypes.Float64Value `tfsdk:"forecast_value"`
	MarketplaceLimitAmount     basetypes.Float64Value `tfsdk:"marketplace_limit_amount"`
	MarketplaceLimitPercentage basetypes.Float64Value `tfsdk:"marketplace_limit_percentage"`
	MarketplaceSpend           basetypes.Float64Value `tfsdk:"marketplace_spend"`
	StartDate                  basetypes.StringValue  `tfsdk:"start_date"`
	state                      attr.ValueState
}

func (v PeriodsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["commitment_value"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["end_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["forecast_value"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["marketplace_limit_amount"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["marketplace_limit_percentage"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["marketplace_spend"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["start_date"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.CommitmentValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["commitment_value"] = val

		val, err = v.EndDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_date"] = val

		val, err = v.ForecastValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["forecast_value"] = val

		val, err = v.MarketplaceLimitAmount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["marketplace_limit_amount"] = val

		val, err = v.MarketplaceLimitPercentage.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["marketplace_limit_percentage"] = val

		val, err = v.MarketplaceSpend.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["marketplace_spend"] = val

		val, err = v.StartDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_date"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PeriodsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PeriodsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PeriodsValue) String() string {
	return "PeriodsValue"
}

func (v PeriodsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"commitment_value":             basetypes.Float64Type{},
		"end_date":                     basetypes.StringType{},
		"forecast_value":               basetypes.Float64Type{},
		"marketplace_limit_amount":     basetypes.Float64Type{},
		"marketplace_limit_percentage": basetypes.Float64Type{},
		"marketplace_spend":            basetypes.Float64Type{},
		"start_date":                   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"commitment_value":             v.CommitmentValue,
			"end_date":                     v.EndDate,
			"forecast_value":               v.ForecastValue,
			"marketplace_limit_amount":     v.MarketplaceLimitAmount,
			"marketplace_limit_percentage": v.MarketplaceLimitPercentage,
			"marketplace_spend":            v.MarketplaceSpend,
			"start_date":                   v.StartDate,
		})

	return objVal, diags
}

func (v PeriodsValue) Equal(o attr.Value) bool {
	other, ok := o.(PeriodsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CommitmentValue.Equal(other.CommitmentValue) {
		return false
	}

	if !v.EndDate.Equal(other.EndDate) {
		return false
	}

	if !v.ForecastValue.Equal(other.ForecastValue) {
		return false
	}

	if !v.MarketplaceLimitAmount.Equal(other.MarketplaceLimitAmount) {
		return false
	}

	if !v.MarketplaceLimitPercentage.Equal(other.MarketplaceLimitPercentage) {
		return false
	}

	if !v.MarketplaceSpend.Equal(other.MarketplaceSpend) {
		return false
	}

	if !v.StartDate.Equal(other.StartDate) {
		return false
	}

	return true
}

func (v PeriodsValue) Type(ctx context.Context) attr.Type {
	return PeriodsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PeriodsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"commitment_value":             basetypes.Float64Type{},
		"end_date":                     basetypes.StringType{},
		"forecast_value":               basetypes.Float64Type{},
		"marketplace_limit_amount":     basetypes.Float64Type{},
		"marketplace_limit_percentage": basetypes.Float64Type{},
		"marketplace_spend":            basetypes.Float64Type{},
		"start_date":                   basetypes.StringType{},
	}
}
