provider:
  name: doit
resources:
  allocation:
    create:
      path: /analytics/v1/allocations
      method: POST
    read:
      path: /analytics/v1/allocations/{id}
      method: GET
    update:
      path: /analytics/v1/allocations/{id}
      method: PATCH
    delete:
      path: /analytics/v1/allocations/{id}
      method: DELETE
