// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_webhook_endpoint

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func WebhookEndpointResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.StringAttribute{
				Computed:            true,
				Description:         "The time when the webhook endpoint was created.",
				MarkdownDescription: "The time when the webhook endpoint was created.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A human-readable description of the webhook endpoint.",
				MarkdownDescription: "A human-readable description of the webhook endpoint.",
			},
			"events": schema.ListAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Computed:            true,
				Description:         "List of event types this endpoint subscribes to. Omit or pass an empty list to subscribe to all events.",
				MarkdownDescription: "List of event types this endpoint subscribes to. Omit or pass an empty list to subscribe to all events.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique identifier of the webhook endpoint.",
				MarkdownDescription: "The unique identifier of the webhook endpoint.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the webhook endpoint.",
				MarkdownDescription: "The name of the webhook endpoint.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The current status of the webhook endpoint.",
				MarkdownDescription: "The current status of the webhook endpoint.",
			},
			"update_time": schema.StringAttribute{
				Computed:            true,
				Description:         "The time when the webhook endpoint was last updated.",
				MarkdownDescription: "The time when the webhook endpoint was last updated.",
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "The URL that receives webhook payloads.",
				MarkdownDescription: "The URL that receives webhook payloads.",
			},
		},
		Description:         "Configure webhooks to receive real-time notifications when events occur in your DoiT environment.",
		MarkdownDescription: "Configure webhooks to receive real-time notifications when events occur in your DoiT environment.",
	}
}

type WebhookEndpointModel struct {
	CreateTime  types.String `tfsdk:"create_time"`
	Description types.String `tfsdk:"description"`
	Events      types.List   `tfsdk:"events"`
	Id          types.String `tfsdk:"id"`
	Name        types.String `tfsdk:"name"`
	Status      types.String `tfsdk:"status"`
	UpdateTime  types.String `tfsdk:"update_time"`
	Url         types.String `tfsdk:"url"`
}
