// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_budget_suggestions

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func BudgetSuggestionsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"items": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"alert_thresholds": schema.ListAttribute{
							ElementType:         types.Float64Type,
							Computed:            true,
							Description:         "Suggested alert thresholds as percentages of the amount.",
							MarkdownDescription: "Suggested alert thresholds as percentages of the amount.",
						},
						"amount": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"amount": schema.StringAttribute{
									Computed:            true,
									Description:         "Decimal string, e.g. \"1234.56\".",
									MarkdownDescription: "Decimal string, e.g. \"1234.56\".",
								},
								"currency": schema.StringAttribute{
									Computed: true,
								},
							},
							CustomType: AmountType{
								ObjectType: types.ObjectType{
									AttrTypes: AmountValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "Suggested budget amount as a decimal-string value with its currency.",
							MarkdownDescription: "Suggested budget amount as a decimal-string value with its currency.",
						},
						"confidence": schema.StringAttribute{
							Computed: true,
						},
						"config": schema.StringAttribute{
							CustomType:          jsontypes.NormalizedType{},
							Computed:            true,
							Description:         "Draft budget configuration to merge over the create-budget defaults. Value is JSON-encoded.",
							MarkdownDescription: "Draft budget configuration to merge over the create-budget defaults. Value is JSON-encoded.",
						},
						"description": schema.StringAttribute{
							Computed: true,
						},
						"generated_time": schema.StringAttribute{
							Computed:            true,
							Description:         "Timestamp when the suggestion was generated.",
							MarkdownDescription: "Timestamp when the suggestion was generated.",
						},
						"id": schema.StringAttribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"rationale": schema.StringAttribute{
							Computed:            true,
							Description:         "Explanation of why this budget is suggested.",
							MarkdownDescription: "Explanation of why this budget is suggested.",
						},
						"scope_chips": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"key": schema.StringAttribute{
										Computed: true,
									},
									"values": schema.ListAttribute{
										ElementType: types.StringType,
										Computed:    true,
									},
								},
								CustomType: ScopeChipsType{
									ObjectType: types.ObjectType{
										AttrTypes: ScopeChipsValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Human-readable summary of the suggested budget scope.",
							MarkdownDescription: "Human-readable summary of the suggested budget scope.",
						},
						"status": schema.StringAttribute{
							Computed: true,
						},
						"time_interval": schema.StringAttribute{
							Computed: true,
						},
					},
					CustomType: ItemsType{
						ObjectType: types.ObjectType{
							AttrTypes: ItemsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Array of pending budget suggestions.",
				MarkdownDescription: "Array of pending budget suggestions.",
			},
			"row_count": schema.Int64Attribute{
				Computed:            true,
				Description:         "Number of suggestions returned.",
				MarkdownDescription: "Number of suggestions returned.",
			},
		},
		Description:         "AI-generated budget recommendations you can accept (link to a budget you created) or dismiss.",
		MarkdownDescription: "AI-generated budget recommendations you can accept (link to a budget you created) or dismiss.",
	}
}

type BudgetSuggestionsModel struct {
	Items    types.List  `tfsdk:"items"`
	RowCount types.Int64 `tfsdk:"row_count"`
}

var _ basetypes.ObjectTypable = ItemsType{}

type ItemsType struct {
	basetypes.ObjectType
}

func (t ItemsType) Equal(o attr.Type) bool {
	other, ok := o.(ItemsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ItemsType) String() string {
	return "ItemsType"
}

func (t ItemsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewItemsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewItemsValueUnknown(), diags
	}

	attributes := in.Attributes()

	alertThresholdsAttribute, ok := attributes["alert_thresholds"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alert_thresholds is missing from object`)

		return nil, diags
	}

	alertThresholdsVal, ok := alertThresholdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alert_thresholds expected to be basetypes.ListValue, was: %T`, alertThresholdsAttribute))
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountValuable, ok := amountAttribute.(basetypes.ObjectValuable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.ObjectValuable, was: %T`, amountAttribute))

		return nil, diags
	}

	amountObjVal, amountObjValDiags := amountValuable.ToObjectValue(ctx)
	diags.Append(amountObjValDiags...)

	amountTypable, ok := t.AttrTypes["amount"].(basetypes.ObjectTypable)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected type to be basetypes.ObjectTypable, was: %T`, t.AttrTypes["amount"]))

		return nil, diags
	}

	amountConverted, amountConvertedDiags := amountTypable.ValueFromObject(ctx, amountObjVal)
	diags.Append(amountConvertedDiags...)

	amountVal, ok := amountConverted.(AmountValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be AmountValue, was: %T`, amountConverted))
	}

	confidenceAttribute, ok := attributes["confidence"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`confidence is missing from object`)

		return nil, diags
	}

	confidenceVal, ok := confidenceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`confidence expected to be basetypes.StringValue, was: %T`, confidenceAttribute))
	}

	configAttribute, ok := attributes["config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config is missing from object`)

		return nil, diags
	}

	configVal, ok := configAttribute.(jsontypes.Normalized)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config expected to be jsontypes.Normalized, was: %T`, configAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	generatedTimeAttribute, ok := attributes["generated_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`generated_time is missing from object`)

		return nil, diags
	}

	generatedTimeVal, ok := generatedTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`generated_time expected to be basetypes.StringValue, was: %T`, generatedTimeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	rationaleAttribute, ok := attributes["rationale"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rationale is missing from object`)

		return nil, diags
	}

	rationaleVal, ok := rationaleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rationale expected to be basetypes.StringValue, was: %T`, rationaleAttribute))
	}

	scopeChipsAttribute, ok := attributes["scope_chips"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope_chips is missing from object`)

		return nil, diags
	}

	scopeChipsVal, ok := scopeChipsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope_chips expected to be basetypes.ListValue, was: %T`, scopeChipsAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	timeIntervalAttribute, ok := attributes["time_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`time_interval is missing from object`)

		return nil, diags
	}

	timeIntervalVal, ok := timeIntervalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`time_interval expected to be basetypes.StringValue, was: %T`, timeIntervalAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ItemsValue{
		AlertThresholds: alertThresholdsVal,
		Amount:          amountVal,
		Confidence:      confidenceVal,
		Config:          configVal,
		Description:     descriptionVal,
		GeneratedTime:   generatedTimeVal,
		Id:              idVal,
		Name:            nameVal,
		Rationale:       rationaleVal,
		ScopeChips:      scopeChipsVal,
		Status:          statusVal,
		TimeInterval:    timeIntervalVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewItemsValueNull() ItemsValue {
	return ItemsValue{
		state: attr.ValueStateNull,
	}
}

func NewItemsValueUnknown() ItemsValue {
	return ItemsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewItemsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ItemsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ItemsValue Attribute Value",
				"While creating a ItemsValue value, a missing attribute value was detected. "+
					"A ItemsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ItemsValue Attribute Type",
				"While creating a ItemsValue value, an invalid attribute value was detected. "+
					"A ItemsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ItemsValue Attribute Value",
				"While creating a ItemsValue value, an extra attribute value was detected. "+
					"A ItemsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ItemsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewItemsValueUnknown(), diags
	}

	alertThresholdsAttribute, ok := attributes["alert_thresholds"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`alert_thresholds is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	alertThresholdsVal, ok := alertThresholdsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`alert_thresholds expected to be basetypes.ListValue, was: %T`, alertThresholdsAttribute))
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(AmountValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be AmountValue, was: %T`, amountAttribute))
	}

	confidenceAttribute, ok := attributes["confidence"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`confidence is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	confidenceVal, ok := confidenceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`confidence expected to be basetypes.StringValue, was: %T`, confidenceAttribute))
	}

	configAttribute, ok := attributes["config"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`config is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	configVal, ok := configAttribute.(jsontypes.Normalized)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`config expected to be jsontypes.Normalized, was: %T`, configAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	generatedTimeAttribute, ok := attributes["generated_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`generated_time is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	generatedTimeVal, ok := generatedTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`generated_time expected to be basetypes.StringValue, was: %T`, generatedTimeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	rationaleAttribute, ok := attributes["rationale"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rationale is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	rationaleVal, ok := rationaleAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rationale expected to be basetypes.StringValue, was: %T`, rationaleAttribute))
	}

	scopeChipsAttribute, ok := attributes["scope_chips"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scope_chips is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	scopeChipsVal, ok := scopeChipsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scope_chips expected to be basetypes.ListValue, was: %T`, scopeChipsAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	timeIntervalAttribute, ok := attributes["time_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`time_interval is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	timeIntervalVal, ok := timeIntervalAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`time_interval expected to be basetypes.StringValue, was: %T`, timeIntervalAttribute))
	}

	if diags.HasError() {
		return NewItemsValueUnknown(), diags
	}

	return ItemsValue{
		AlertThresholds: alertThresholdsVal,
		Amount:          amountVal,
		Confidence:      confidenceVal,
		Config:          configVal,
		Description:     descriptionVal,
		GeneratedTime:   generatedTimeVal,
		Id:              idVal,
		Name:            nameVal,
		Rationale:       rationaleVal,
		ScopeChips:      scopeChipsVal,
		Status:          statusVal,
		TimeInterval:    timeIntervalVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewItemsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ItemsValue {
	object, diags := NewItemsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewItemsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ItemsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewItemsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewItemsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewItemsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewItemsValueMust(ItemsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ItemsType) ValueType(ctx context.Context) attr.Value {
	return ItemsValue{}
}

var _ basetypes.ObjectValuable = ItemsValue{}

type ItemsValue struct {
	AlertThresholds basetypes.ListValue   `tfsdk:"alert_thresholds"`
	Amount          AmountValue           `tfsdk:"amount"`
	Confidence      basetypes.StringValue `tfsdk:"confidence"`
	Config          jsontypes.Normalized  `tfsdk:"config"`
	Description     basetypes.StringValue `tfsdk:"description"`
	GeneratedTime   basetypes.StringValue `tfsdk:"generated_time"`
	Id              basetypes.StringValue `tfsdk:"id"`
	Name            basetypes.StringValue `tfsdk:"name"`
	Rationale       basetypes.StringValue `tfsdk:"rationale"`
	ScopeChips      basetypes.ListValue   `tfsdk:"scope_chips"`
	Status          basetypes.StringValue `tfsdk:"status"`
	TimeInterval    basetypes.StringValue `tfsdk:"time_interval"`
	state           attr.ValueState
}

func (v ItemsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 12)

	var val tftypes.Value
	var err error

	attrTypes["alert_thresholds"] = basetypes.ListType{
		ElemType: types.Float64Type,
	}.TerraformType(ctx)
	attrTypes["amount"] = AmountType{
		basetypes.ObjectType{
			AttrTypes: AmountValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["confidence"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["config"] = jsontypes.NormalizedType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["generated_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["rationale"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["scope_chips"] = basetypes.ListType{
		ElemType: ScopeChipsValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["time_interval"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 12)

		val, err = v.AlertThresholds.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["alert_thresholds"] = val

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		val, err = v.Confidence.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["confidence"] = val

		val, err = v.Config.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["config"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.GeneratedTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["generated_time"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Rationale.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rationale"] = val

		val, err = v.ScopeChips.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scope_chips"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.TimeInterval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["time_interval"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ItemsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ItemsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ItemsValue) String() string {
	return "ItemsValue"
}

func (v ItemsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var amount attr.Value

	{
		amount = v.Amount
	}

	var scopeChips attr.Value

	{
		scopeChips = v.ScopeChips
	}

	var alertThresholdsVal basetypes.ListValue
	switch {
	case v.AlertThresholds.IsUnknown():
		alertThresholdsVal = types.ListUnknown(types.Float64Type)
	case v.AlertThresholds.IsNull():
		alertThresholdsVal = types.ListNull(types.Float64Type)
	default:
		var d diag.Diagnostics
		alertThresholdsVal, d = types.ListValue(types.Float64Type, v.AlertThresholds.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"alert_thresholds": basetypes.ListType{
				ElemType: types.Float64Type,
			},
			"amount": AmountType{
				basetypes.ObjectType{
					AttrTypes: AmountValue{}.AttributeTypes(ctx),
				},
			},
			"confidence":     basetypes.StringType{},
			"config":         jsontypes.NormalizedType{},
			"description":    basetypes.StringType{},
			"generated_time": basetypes.StringType{},
			"id":             basetypes.StringType{},
			"name":           basetypes.StringType{},
			"rationale":      basetypes.StringType{},
			"scope_chips": basetypes.ListType{
				ElemType: ScopeChipsValue{}.Type(ctx),
			},
			"status":        basetypes.StringType{},
			"time_interval": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"alert_thresholds": basetypes.ListType{
			ElemType: types.Float64Type,
		},
		"amount": AmountType{
			basetypes.ObjectType{
				AttrTypes: AmountValue{}.AttributeTypes(ctx),
			},
		},
		"confidence":     basetypes.StringType{},
		"config":         jsontypes.NormalizedType{},
		"description":    basetypes.StringType{},
		"generated_time": basetypes.StringType{},
		"id":             basetypes.StringType{},
		"name":           basetypes.StringType{},
		"rationale":      basetypes.StringType{},
		"scope_chips": basetypes.ListType{
			ElemType: ScopeChipsValue{}.Type(ctx),
		},
		"status":        basetypes.StringType{},
		"time_interval": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"alert_thresholds": alertThresholdsVal,
			"amount":           amount,
			"confidence":       v.Confidence,
			"config":           v.Config,
			"description":      v.Description,
			"generated_time":   v.GeneratedTime,
			"id":               v.Id,
			"name":             v.Name,
			"rationale":        v.Rationale,
			"scope_chips":      scopeChips,
			"status":           v.Status,
			"time_interval":    v.TimeInterval,
		})

	return objVal, diags
}

func (v ItemsValue) Equal(o attr.Value) bool {
	other, ok := o.(ItemsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.AlertThresholds.Equal(other.AlertThresholds) {
		return false
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	if !v.Confidence.Equal(other.Confidence) {
		return false
	}

	if !v.Config.Equal(other.Config) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.GeneratedTime.Equal(other.GeneratedTime) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Rationale.Equal(other.Rationale) {
		return false
	}

	if !v.ScopeChips.Equal(other.ScopeChips) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.TimeInterval.Equal(other.TimeInterval) {
		return false
	}

	return true
}

func (v ItemsValue) Type(ctx context.Context) attr.Type {
	return ItemsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ItemsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"alert_thresholds": basetypes.ListType{
			ElemType: types.Float64Type,
		},
		"amount": AmountType{
			basetypes.ObjectType{
				AttrTypes: AmountValue{}.AttributeTypes(ctx),
			},
		},
		"confidence":     basetypes.StringType{},
		"config":         jsontypes.NormalizedType{},
		"description":    basetypes.StringType{},
		"generated_time": basetypes.StringType{},
		"id":             basetypes.StringType{},
		"name":           basetypes.StringType{},
		"rationale":      basetypes.StringType{},
		"scope_chips": basetypes.ListType{
			ElemType: ScopeChipsValue{}.Type(ctx),
		},
		"status":        basetypes.StringType{},
		"time_interval": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = AmountType{}

type AmountType struct {
	basetypes.ObjectType
}

func (t AmountType) Equal(o attr.Type) bool {
	other, ok := o.(AmountType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AmountType) String() string {
	return "AmountType"
}

func (t AmountType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewAmountValueNull(), diags
	}

	if in.IsUnknown() {
		return NewAmountValueUnknown(), diags
	}

	attributes := in.Attributes()

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return nil, diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return nil, diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AmountValue{
		Amount:   amountVal,
		Currency: currencyVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewAmountValueNull() AmountValue {
	return AmountValue{
		state: attr.ValueStateNull,
	}
}

func NewAmountValueUnknown() AmountValue {
	return AmountValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAmountValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AmountValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AmountValue Attribute Value",
				"While creating a AmountValue value, a missing attribute value was detected. "+
					"A AmountValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AmountValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AmountValue Attribute Type",
				"While creating a AmountValue value, an invalid attribute value was detected. "+
					"A AmountValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AmountValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AmountValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AmountValue Attribute Value",
				"While creating a AmountValue value, an extra attribute value was detected. "+
					"A AmountValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AmountValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAmountValueUnknown(), diags
	}

	amountAttribute, ok := attributes["amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`amount is missing from object`)

		return NewAmountValueUnknown(), diags
	}

	amountVal, ok := amountAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`amount expected to be basetypes.StringValue, was: %T`, amountAttribute))
	}

	currencyAttribute, ok := attributes["currency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`currency is missing from object`)

		return NewAmountValueUnknown(), diags
	}

	currencyVal, ok := currencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`currency expected to be basetypes.StringValue, was: %T`, currencyAttribute))
	}

	if diags.HasError() {
		return NewAmountValueUnknown(), diags
	}

	return AmountValue{
		Amount:   amountVal,
		Currency: currencyVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewAmountValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AmountValue {
	object, diags := NewAmountValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAmountValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AmountType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAmountValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAmountValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAmountValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAmountValueMust(AmountValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AmountType) ValueType(ctx context.Context) attr.Value {
	return AmountValue{}
}

var _ basetypes.ObjectValuable = AmountValue{}

type AmountValue struct {
	Amount   basetypes.StringValue `tfsdk:"amount"`
	Currency basetypes.StringValue `tfsdk:"currency"`
	state    attr.ValueState
}

func (v AmountValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["amount"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["currency"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Amount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["amount"] = val

		val, err = v.Currency.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["currency"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AmountValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AmountValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AmountValue) String() string {
	return "AmountValue"
}

func (v AmountValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"amount":   basetypes.StringType{},
		"currency": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"amount":   v.Amount,
			"currency": v.Currency,
		})

	return objVal, diags
}

func (v AmountValue) Equal(o attr.Value) bool {
	other, ok := o.(AmountValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Amount.Equal(other.Amount) {
		return false
	}

	if !v.Currency.Equal(other.Currency) {
		return false
	}

	return true
}

func (v AmountValue) Type(ctx context.Context) attr.Type {
	return AmountType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AmountValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"amount":   basetypes.StringType{},
		"currency": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ScopeChipsType{}

type ScopeChipsType struct {
	basetypes.ObjectType
}

func (t ScopeChipsType) Equal(o attr.Type) bool {
	other, ok := o.(ScopeChipsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScopeChipsType) String() string {
	return "ScopeChipsType"
}

func (t ScopeChipsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewScopeChipsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewScopeChipsValueUnknown(), diags
	}

	attributes := in.Attributes()

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	valuesAttribute, ok := attributes["values"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`values is missing from object`)

		return nil, diags
	}

	valuesVal, ok := valuesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`values expected to be basetypes.ListValue, was: %T`, valuesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScopeChipsValue{
		Key:    keyVal,
		Values: valuesVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewScopeChipsValueNull() ScopeChipsValue {
	return ScopeChipsValue{
		state: attr.ValueStateNull,
	}
}

func NewScopeChipsValueUnknown() ScopeChipsValue {
	return ScopeChipsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScopeChipsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScopeChipsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScopeChipsValue Attribute Value",
				"While creating a ScopeChipsValue value, a missing attribute value was detected. "+
					"A ScopeChipsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopeChipsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScopeChipsValue Attribute Type",
				"While creating a ScopeChipsValue value, an invalid attribute value was detected. "+
					"A ScopeChipsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScopeChipsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScopeChipsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScopeChipsValue Attribute Value",
				"While creating a ScopeChipsValue value, an extra attribute value was detected. "+
					"A ScopeChipsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScopeChipsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScopeChipsValueUnknown(), diags
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewScopeChipsValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	valuesAttribute, ok := attributes["values"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`values is missing from object`)

		return NewScopeChipsValueUnknown(), diags
	}

	valuesVal, ok := valuesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`values expected to be basetypes.ListValue, was: %T`, valuesAttribute))
	}

	if diags.HasError() {
		return NewScopeChipsValueUnknown(), diags
	}

	return ScopeChipsValue{
		Key:    keyVal,
		Values: valuesVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewScopeChipsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScopeChipsValue {
	object, diags := NewScopeChipsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScopeChipsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScopeChipsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScopeChipsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScopeChipsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScopeChipsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScopeChipsValueMust(ScopeChipsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScopeChipsType) ValueType(ctx context.Context) attr.Value {
	return ScopeChipsValue{}
}

var _ basetypes.ObjectValuable = ScopeChipsValue{}

type ScopeChipsValue struct {
	Key    basetypes.StringValue `tfsdk:"key"`
	Values basetypes.ListValue   `tfsdk:"values"`
	state  attr.ValueState
}

func (v ScopeChipsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["values"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Values.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["values"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScopeChipsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScopeChipsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScopeChipsValue) String() string {
	return "ScopeChipsValue"
}

func (v ScopeChipsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var valuesVal basetypes.ListValue
	switch {
	case v.Values.IsUnknown():
		valuesVal = types.ListUnknown(types.StringType)
	case v.Values.IsNull():
		valuesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		valuesVal, d = types.ListValue(types.StringType, v.Values.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"key": basetypes.StringType{},
			"values": basetypes.ListType{
				ElemType: types.StringType,
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"key": basetypes.StringType{},
		"values": basetypes.ListType{
			ElemType: types.StringType,
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"key":    v.Key,
			"values": valuesVal,
		})

	return objVal, diags
}

func (v ScopeChipsValue) Equal(o attr.Value) bool {
	other, ok := o.(ScopeChipsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Values.Equal(other.Values) {
		return false
	}

	return true
}

func (v ScopeChipsValue) Type(ctx context.Context) attr.Type {
	return ScopeChipsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScopeChipsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"key": basetypes.StringType{},
		"values": basetypes.ListType{
			ElemType: types.StringType,
		},
	}
}
