// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_asset

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AssetResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.Int64Attribute{
				Computed:            true,
				Description:         "The time when the asset was created, in milliseconds since the epoch.",
				MarkdownDescription: "The time when the asset was created, in milliseconds since the epoch.",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The unique id of an asset.",
				MarkdownDescription: "The unique id of an asset.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"properties": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"customer_domain": schema.StringAttribute{
						Computed:            true,
						Description:         "",
						MarkdownDescription: "",
					},
					"customer_id": schema.StringAttribute{
						Computed:            true,
						Description:         "",
						MarkdownDescription: "",
					},
					"reseller": schema.StringAttribute{
						Computed:            true,
						Description:         "",
						MarkdownDescription: "",
					},
					"subscription": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"billing_method": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
							"creation_time": schema.Int64Attribute{
								Computed: true,
							},
							"id": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
							"plan": schema.SingleNestedAttribute{
								Attributes: map[string]schema.Attribute{
									"commitment_interval": schema.SingleNestedAttribute{
										Attributes: map[string]schema.Attribute{
											"end_time": schema.Int64Attribute{
												Computed: true,
											},
											"start_time": schema.Int64Attribute{
												Computed: true,
											},
										},
										CustomType: CommitmentIntervalType{
											ObjectType: types.ObjectType{
												AttrTypes: CommitmentIntervalValue{}.AttributeTypes(ctx),
											},
										},
										Computed:            true,
										Description:         "Subscription-related metadata for an asset.",
										MarkdownDescription: "Subscription-related metadata for an asset.",
									},
									"is_commitment_plan": schema.BoolAttribute{
										Computed: true,
									},
									"plan_name": schema.StringAttribute{
										Computed:            true,
										Description:         "",
										MarkdownDescription: "",
									},
								},
								CustomType: PlanType{
									ObjectType: types.ObjectType{
										AttrTypes: PlanValue{}.AttributeTypes(ctx),
									},
								},
								Computed:            true,
								Description:         "Subscription-related metadata for an asset.",
								MarkdownDescription: "Subscription-related metadata for an asset.",
							},
							"purchase_order_id": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
							"renewal_settings": schema.SingleNestedAttribute{
								Attributes: map[string]schema.Attribute{
									"renewal_type": schema.StringAttribute{
										Computed:            true,
										Description:         "",
										MarkdownDescription: "",
									},
								},
								CustomType: RenewalSettingsType{
									ObjectType: types.ObjectType{
										AttrTypes: RenewalSettingsValue{}.AttributeTypes(ctx),
									},
								},
								Computed:            true,
								Description:         "Settings that control subscription renewal behavior.",
								MarkdownDescription: "Settings that control subscription renewal behavior.",
							},
							"resource_uiurl": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
							"seats": schema.SingleNestedAttribute{
								Attributes: map[string]schema.Attribute{
									"licensed_number_of_seats": schema.Int64Attribute{
										Computed: true,
									},
									"maximum_number_of_seats": schema.Int64Attribute{
										Computed: true,
									},
									"number_of_seats": schema.Int64Attribute{
										Computed: true,
									},
								},
								CustomType: SeatsType{
									ObjectType: types.ObjectType{
										AttrTypes: SeatsValue{}.AttributeTypes(ctx),
									},
								},
								Computed:            true,
								Description:         "Licensing seat counts for a subscription or asset.",
								MarkdownDescription: "Licensing seat counts for a subscription or asset.",
							},
							"sku_id": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
							"sku_name": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
							"status": schema.StringAttribute{
								Computed:            true,
								Description:         "",
								MarkdownDescription: "",
							},
						},
						CustomType: SubscriptionType{
							ObjectType: types.ObjectType{
								AttrTypes: SubscriptionValue{}.AttributeTypes(ctx),
							},
						},
						Computed:            true,
						Description:         "Subscription-related metadata for an asset.",
						MarkdownDescription: "Subscription-related metadata for an asset.",
					},
				},
				CustomType: PropertiesType{
					ObjectType: types.ObjectType{
						AttrTypes: PropertiesValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Additional properties associated with an asset.",
				MarkdownDescription: "Additional properties associated with an asset.",
			},
			"quantity": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
			"url": schema.StringAttribute{
				Computed:            true,
				Description:         "",
				MarkdownDescription: "",
			},
		},
		Description:         "Manage cloud resources or services in your cloud environment.",
		MarkdownDescription: "Manage cloud resources or services in your cloud environment.",
	}
}

type AssetModel struct {
	CreateTime types.Int64     `tfsdk:"create_time"`
	Id         types.String    `tfsdk:"id"`
	Name       types.String    `tfsdk:"name"`
	Properties PropertiesValue `tfsdk:"properties"`
	Quantity   types.Int64     `tfsdk:"quantity"`
	Type       types.String    `tfsdk:"type"`
	Url        types.String    `tfsdk:"url"`
}

var _ basetypes.ObjectTypable = PropertiesType{}

type PropertiesType struct {
	basetypes.ObjectType
}

func (t PropertiesType) Equal(o attr.Type) bool {
	other, ok := o.(PropertiesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PropertiesType) String() string {
	return "PropertiesType"
}

func (t PropertiesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	customerDomainAttribute, ok := attributes["customer_domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`customer_domain is missing from object`)

		return nil, diags
	}

	customerDomainVal, ok := customerDomainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`customer_domain expected to be basetypes.StringValue, was: %T`, customerDomainAttribute))
	}

	customerIdAttribute, ok := attributes["customer_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`customer_id is missing from object`)

		return nil, diags
	}

	customerIdVal, ok := customerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`customer_id expected to be basetypes.StringValue, was: %T`, customerIdAttribute))
	}

	resellerAttribute, ok := attributes["reseller"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reseller is missing from object`)

		return nil, diags
	}

	resellerVal, ok := resellerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reseller expected to be basetypes.StringValue, was: %T`, resellerAttribute))
	}

	subscriptionAttribute, ok := attributes["subscription"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`subscription is missing from object`)

		return nil, diags
	}

	subscriptionVal, ok := subscriptionAttribute.(SubscriptionValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`subscription expected to be SubscriptionValue, was: %T`, subscriptionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PropertiesValue{
		CustomerDomain: customerDomainVal,
		CustomerId:     customerIdVal,
		Reseller:       resellerVal,
		Subscription:   subscriptionVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewPropertiesValueNull() PropertiesValue {
	return PropertiesValue{
		state: attr.ValueStateNull,
	}
}

func NewPropertiesValueUnknown() PropertiesValue {
	return PropertiesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPropertiesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PropertiesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PropertiesValue Attribute Value",
				"While creating a PropertiesValue value, a missing attribute value was detected. "+
					"A PropertiesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PropertiesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PropertiesValue Attribute Type",
				"While creating a PropertiesValue value, an invalid attribute value was detected. "+
					"A PropertiesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PropertiesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PropertiesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PropertiesValue Attribute Value",
				"While creating a PropertiesValue value, an extra attribute value was detected. "+
					"A PropertiesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PropertiesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPropertiesValueUnknown(), diags
	}

	customerDomainAttribute, ok := attributes["customer_domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`customer_domain is missing from object`)

		return NewPropertiesValueUnknown(), diags
	}

	customerDomainVal, ok := customerDomainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`customer_domain expected to be basetypes.StringValue, was: %T`, customerDomainAttribute))
	}

	customerIdAttribute, ok := attributes["customer_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`customer_id is missing from object`)

		return NewPropertiesValueUnknown(), diags
	}

	customerIdVal, ok := customerIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`customer_id expected to be basetypes.StringValue, was: %T`, customerIdAttribute))
	}

	resellerAttribute, ok := attributes["reseller"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reseller is missing from object`)

		return NewPropertiesValueUnknown(), diags
	}

	resellerVal, ok := resellerAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reseller expected to be basetypes.StringValue, was: %T`, resellerAttribute))
	}

	subscriptionAttribute, ok := attributes["subscription"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`subscription is missing from object`)

		return NewPropertiesValueUnknown(), diags
	}

	subscriptionVal, ok := subscriptionAttribute.(SubscriptionValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`subscription expected to be SubscriptionValue, was: %T`, subscriptionAttribute))
	}

	if diags.HasError() {
		return NewPropertiesValueUnknown(), diags
	}

	return PropertiesValue{
		CustomerDomain: customerDomainVal,
		CustomerId:     customerIdVal,
		Reseller:       resellerVal,
		Subscription:   subscriptionVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewPropertiesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PropertiesValue {
	object, diags := NewPropertiesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPropertiesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PropertiesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPropertiesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPropertiesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPropertiesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPropertiesValueMust(PropertiesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PropertiesType) ValueType(ctx context.Context) attr.Value {
	return PropertiesValue{}
}

var _ basetypes.ObjectValuable = PropertiesValue{}

type PropertiesValue struct {
	CustomerDomain basetypes.StringValue `tfsdk:"customer_domain"`
	CustomerId     basetypes.StringValue `tfsdk:"customer_id"`
	Reseller       basetypes.StringValue `tfsdk:"reseller"`
	Subscription   SubscriptionValue     `tfsdk:"subscription"`
	state          attr.ValueState
}

func (v PropertiesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["customer_domain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["customer_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["reseller"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["subscription"] = SubscriptionType{
		basetypes.ObjectType{
			AttrTypes: SubscriptionValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.CustomerDomain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["customer_domain"] = val

		val, err = v.CustomerId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["customer_id"] = val

		val, err = v.Reseller.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["reseller"] = val

		val, err = v.Subscription.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["subscription"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PropertiesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PropertiesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PropertiesValue) String() string {
	return "PropertiesValue"
}

func (v PropertiesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var subscription attr.Value

	{
		subscription = v.Subscription
	}

	attributeTypes := map[string]attr.Type{
		"customer_domain": basetypes.StringType{},
		"customer_id":     basetypes.StringType{},
		"reseller":        basetypes.StringType{},
		"subscription": SubscriptionType{
			basetypes.ObjectType{
				AttrTypes: SubscriptionValue{}.AttributeTypes(ctx),
			},
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"customer_domain": v.CustomerDomain,
			"customer_id":     v.CustomerId,
			"reseller":        v.Reseller,
			"subscription":    subscription,
		})

	return objVal, diags
}

func (v PropertiesValue) Equal(o attr.Value) bool {
	other, ok := o.(PropertiesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CustomerDomain.Equal(other.CustomerDomain) {
		return false
	}

	if !v.CustomerId.Equal(other.CustomerId) {
		return false
	}

	if !v.Reseller.Equal(other.Reseller) {
		return false
	}

	if !v.Subscription.Equal(other.Subscription) {
		return false
	}

	return true
}

func (v PropertiesValue) Type(ctx context.Context) attr.Type {
	return PropertiesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PropertiesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"customer_domain": basetypes.StringType{},
		"customer_id":     basetypes.StringType{},
		"reseller":        basetypes.StringType{},
		"subscription": SubscriptionType{
			basetypes.ObjectType{
				AttrTypes: SubscriptionValue{}.AttributeTypes(ctx),
			},
		},
	}
}

var _ basetypes.ObjectTypable = SubscriptionType{}

type SubscriptionType struct {
	basetypes.ObjectType
}

func (t SubscriptionType) Equal(o attr.Type) bool {
	other, ok := o.(SubscriptionType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SubscriptionType) String() string {
	return "SubscriptionType"
}

func (t SubscriptionType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	billingMethodAttribute, ok := attributes["billing_method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`billing_method is missing from object`)

		return nil, diags
	}

	billingMethodVal, ok := billingMethodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`billing_method expected to be basetypes.StringValue, was: %T`, billingMethodAttribute))
	}

	creationTimeAttribute, ok := attributes["creation_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`creation_time is missing from object`)

		return nil, diags
	}

	creationTimeVal, ok := creationTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`creation_time expected to be basetypes.Int64Value, was: %T`, creationTimeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	planAttribute, ok := attributes["plan"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan is missing from object`)

		return nil, diags
	}

	planVal, ok := planAttribute.(PlanValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan expected to be PlanValue, was: %T`, planAttribute))
	}

	purchaseOrderIdAttribute, ok := attributes["purchase_order_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`purchase_order_id is missing from object`)

		return nil, diags
	}

	purchaseOrderIdVal, ok := purchaseOrderIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`purchase_order_id expected to be basetypes.StringValue, was: %T`, purchaseOrderIdAttribute))
	}

	renewalSettingsAttribute, ok := attributes["renewal_settings"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`renewal_settings is missing from object`)

		return nil, diags
	}

	renewalSettingsVal, ok := renewalSettingsAttribute.(RenewalSettingsValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`renewal_settings expected to be RenewalSettingsValue, was: %T`, renewalSettingsAttribute))
	}

	resourceUiurlAttribute, ok := attributes["resource_uiurl"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`resource_uiurl is missing from object`)

		return nil, diags
	}

	resourceUiurlVal, ok := resourceUiurlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`resource_uiurl expected to be basetypes.StringValue, was: %T`, resourceUiurlAttribute))
	}

	seatsAttribute, ok := attributes["seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`seats is missing from object`)

		return nil, diags
	}

	seatsVal, ok := seatsAttribute.(SeatsValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`seats expected to be SeatsValue, was: %T`, seatsAttribute))
	}

	skuIdAttribute, ok := attributes["sku_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sku_id is missing from object`)

		return nil, diags
	}

	skuIdVal, ok := skuIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sku_id expected to be basetypes.StringValue, was: %T`, skuIdAttribute))
	}

	skuNameAttribute, ok := attributes["sku_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sku_name is missing from object`)

		return nil, diags
	}

	skuNameVal, ok := skuNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sku_name expected to be basetypes.StringValue, was: %T`, skuNameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SubscriptionValue{
		BillingMethod:   billingMethodVal,
		CreationTime:    creationTimeVal,
		Id:              idVal,
		Plan:            planVal,
		PurchaseOrderId: purchaseOrderIdVal,
		RenewalSettings: renewalSettingsVal,
		ResourceUiurl:   resourceUiurlVal,
		Seats:           seatsVal,
		SkuId:           skuIdVal,
		SkuName:         skuNameVal,
		Status:          statusVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewSubscriptionValueNull() SubscriptionValue {
	return SubscriptionValue{
		state: attr.ValueStateNull,
	}
}

func NewSubscriptionValueUnknown() SubscriptionValue {
	return SubscriptionValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSubscriptionValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SubscriptionValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SubscriptionValue Attribute Value",
				"While creating a SubscriptionValue value, a missing attribute value was detected. "+
					"A SubscriptionValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SubscriptionValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SubscriptionValue Attribute Type",
				"While creating a SubscriptionValue value, an invalid attribute value was detected. "+
					"A SubscriptionValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SubscriptionValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SubscriptionValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SubscriptionValue Attribute Value",
				"While creating a SubscriptionValue value, an extra attribute value was detected. "+
					"A SubscriptionValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SubscriptionValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSubscriptionValueUnknown(), diags
	}

	billingMethodAttribute, ok := attributes["billing_method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`billing_method is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	billingMethodVal, ok := billingMethodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`billing_method expected to be basetypes.StringValue, was: %T`, billingMethodAttribute))
	}

	creationTimeAttribute, ok := attributes["creation_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`creation_time is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	creationTimeVal, ok := creationTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`creation_time expected to be basetypes.Int64Value, was: %T`, creationTimeAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	planAttribute, ok := attributes["plan"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	planVal, ok := planAttribute.(PlanValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan expected to be PlanValue, was: %T`, planAttribute))
	}

	purchaseOrderIdAttribute, ok := attributes["purchase_order_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`purchase_order_id is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	purchaseOrderIdVal, ok := purchaseOrderIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`purchase_order_id expected to be basetypes.StringValue, was: %T`, purchaseOrderIdAttribute))
	}

	renewalSettingsAttribute, ok := attributes["renewal_settings"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`renewal_settings is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	renewalSettingsVal, ok := renewalSettingsAttribute.(RenewalSettingsValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`renewal_settings expected to be RenewalSettingsValue, was: %T`, renewalSettingsAttribute))
	}

	resourceUiurlAttribute, ok := attributes["resource_uiurl"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`resource_uiurl is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	resourceUiurlVal, ok := resourceUiurlAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`resource_uiurl expected to be basetypes.StringValue, was: %T`, resourceUiurlAttribute))
	}

	seatsAttribute, ok := attributes["seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`seats is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	seatsVal, ok := seatsAttribute.(SeatsValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`seats expected to be SeatsValue, was: %T`, seatsAttribute))
	}

	skuIdAttribute, ok := attributes["sku_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sku_id is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	skuIdVal, ok := skuIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sku_id expected to be basetypes.StringValue, was: %T`, skuIdAttribute))
	}

	skuNameAttribute, ok := attributes["sku_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sku_name is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	skuNameVal, ok := skuNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sku_name expected to be basetypes.StringValue, was: %T`, skuNameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewSubscriptionValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	if diags.HasError() {
		return NewSubscriptionValueUnknown(), diags
	}

	return SubscriptionValue{
		BillingMethod:   billingMethodVal,
		CreationTime:    creationTimeVal,
		Id:              idVal,
		Plan:            planVal,
		PurchaseOrderId: purchaseOrderIdVal,
		RenewalSettings: renewalSettingsVal,
		ResourceUiurl:   resourceUiurlVal,
		Seats:           seatsVal,
		SkuId:           skuIdVal,
		SkuName:         skuNameVal,
		Status:          statusVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewSubscriptionValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SubscriptionValue {
	object, diags := NewSubscriptionValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSubscriptionValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SubscriptionType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSubscriptionValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSubscriptionValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSubscriptionValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSubscriptionValueMust(SubscriptionValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SubscriptionType) ValueType(ctx context.Context) attr.Value {
	return SubscriptionValue{}
}

var _ basetypes.ObjectValuable = SubscriptionValue{}

type SubscriptionValue struct {
	BillingMethod   basetypes.StringValue `tfsdk:"billing_method"`
	CreationTime    basetypes.Int64Value  `tfsdk:"creation_time"`
	Id              basetypes.StringValue `tfsdk:"id"`
	Plan            PlanValue             `tfsdk:"plan"`
	PurchaseOrderId basetypes.StringValue `tfsdk:"purchase_order_id"`
	RenewalSettings RenewalSettingsValue  `tfsdk:"renewal_settings"`
	ResourceUiurl   basetypes.StringValue `tfsdk:"resource_uiurl"`
	Seats           SeatsValue            `tfsdk:"seats"`
	SkuId           basetypes.StringValue `tfsdk:"sku_id"`
	SkuName         basetypes.StringValue `tfsdk:"sku_name"`
	Status          basetypes.StringValue `tfsdk:"status"`
	state           attr.ValueState
}

func (v SubscriptionValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 11)

	var val tftypes.Value
	var err error

	attrTypes["billing_method"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["creation_time"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["plan"] = PlanType{
		basetypes.ObjectType{
			AttrTypes: PlanValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["purchase_order_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["renewal_settings"] = RenewalSettingsType{
		basetypes.ObjectType{
			AttrTypes: RenewalSettingsValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["resource_uiurl"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["seats"] = SeatsType{
		basetypes.ObjectType{
			AttrTypes: SeatsValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["sku_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["sku_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 11)

		val, err = v.BillingMethod.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["billing_method"] = val

		val, err = v.CreationTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["creation_time"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Plan.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plan"] = val

		val, err = v.PurchaseOrderId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["purchase_order_id"] = val

		val, err = v.RenewalSettings.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["renewal_settings"] = val

		val, err = v.ResourceUiurl.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["resource_uiurl"] = val

		val, err = v.Seats.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["seats"] = val

		val, err = v.SkuId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["sku_id"] = val

		val, err = v.SkuName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["sku_name"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SubscriptionValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SubscriptionValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SubscriptionValue) String() string {
	return "SubscriptionValue"
}

func (v SubscriptionValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var plan attr.Value

	{
		plan = v.Plan
	}

	var renewalSettings attr.Value

	{
		renewalSettings = v.RenewalSettings
	}

	var seats attr.Value

	{
		seats = v.Seats
	}

	attributeTypes := map[string]attr.Type{
		"billing_method": basetypes.StringType{},
		"creation_time":  basetypes.Int64Type{},
		"id":             basetypes.StringType{},
		"plan": PlanType{
			basetypes.ObjectType{
				AttrTypes: PlanValue{}.AttributeTypes(ctx),
			},
		},
		"purchase_order_id": basetypes.StringType{},
		"renewal_settings": RenewalSettingsType{
			basetypes.ObjectType{
				AttrTypes: RenewalSettingsValue{}.AttributeTypes(ctx),
			},
		},
		"resource_uiurl": basetypes.StringType{},
		"seats": SeatsType{
			basetypes.ObjectType{
				AttrTypes: SeatsValue{}.AttributeTypes(ctx),
			},
		},
		"sku_id":   basetypes.StringType{},
		"sku_name": basetypes.StringType{},
		"status":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"billing_method":    v.BillingMethod,
			"creation_time":     v.CreationTime,
			"id":                v.Id,
			"plan":              plan,
			"purchase_order_id": v.PurchaseOrderId,
			"renewal_settings":  renewalSettings,
			"resource_uiurl":    v.ResourceUiurl,
			"seats":             seats,
			"sku_id":            v.SkuId,
			"sku_name":          v.SkuName,
			"status":            v.Status,
		})

	return objVal, diags
}

func (v SubscriptionValue) Equal(o attr.Value) bool {
	other, ok := o.(SubscriptionValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.BillingMethod.Equal(other.BillingMethod) {
		return false
	}

	if !v.CreationTime.Equal(other.CreationTime) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Plan.Equal(other.Plan) {
		return false
	}

	if !v.PurchaseOrderId.Equal(other.PurchaseOrderId) {
		return false
	}

	if !v.RenewalSettings.Equal(other.RenewalSettings) {
		return false
	}

	if !v.ResourceUiurl.Equal(other.ResourceUiurl) {
		return false
	}

	if !v.Seats.Equal(other.Seats) {
		return false
	}

	if !v.SkuId.Equal(other.SkuId) {
		return false
	}

	if !v.SkuName.Equal(other.SkuName) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	return true
}

func (v SubscriptionValue) Type(ctx context.Context) attr.Type {
	return SubscriptionType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SubscriptionValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"billing_method": basetypes.StringType{},
		"creation_time":  basetypes.Int64Type{},
		"id":             basetypes.StringType{},
		"plan": PlanType{
			basetypes.ObjectType{
				AttrTypes: PlanValue{}.AttributeTypes(ctx),
			},
		},
		"purchase_order_id": basetypes.StringType{},
		"renewal_settings": RenewalSettingsType{
			basetypes.ObjectType{
				AttrTypes: RenewalSettingsValue{}.AttributeTypes(ctx),
			},
		},
		"resource_uiurl": basetypes.StringType{},
		"seats": SeatsType{
			basetypes.ObjectType{
				AttrTypes: SeatsValue{}.AttributeTypes(ctx),
			},
		},
		"sku_id":   basetypes.StringType{},
		"sku_name": basetypes.StringType{},
		"status":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PlanType{}

type PlanType struct {
	basetypes.ObjectType
}

func (t PlanType) Equal(o attr.Type) bool {
	other, ok := o.(PlanType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PlanType) String() string {
	return "PlanType"
}

func (t PlanType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	commitmentIntervalAttribute, ok := attributes["commitment_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_interval is missing from object`)

		return nil, diags
	}

	commitmentIntervalVal, ok := commitmentIntervalAttribute.(CommitmentIntervalValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_interval expected to be CommitmentIntervalValue, was: %T`, commitmentIntervalAttribute))
	}

	isCommitmentPlanAttribute, ok := attributes["is_commitment_plan"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_commitment_plan is missing from object`)

		return nil, diags
	}

	isCommitmentPlanVal, ok := isCommitmentPlanAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_commitment_plan expected to be basetypes.BoolValue, was: %T`, isCommitmentPlanAttribute))
	}

	planNameAttribute, ok := attributes["plan_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_name is missing from object`)

		return nil, diags
	}

	planNameVal, ok := planNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_name expected to be basetypes.StringValue, was: %T`, planNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PlanValue{
		CommitmentInterval: commitmentIntervalVal,
		IsCommitmentPlan:   isCommitmentPlanVal,
		PlanName:           planNameVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewPlanValueNull() PlanValue {
	return PlanValue{
		state: attr.ValueStateNull,
	}
}

func NewPlanValueUnknown() PlanValue {
	return PlanValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPlanValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PlanValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PlanValue Attribute Value",
				"While creating a PlanValue value, a missing attribute value was detected. "+
					"A PlanValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PlanValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PlanValue Attribute Type",
				"While creating a PlanValue value, an invalid attribute value was detected. "+
					"A PlanValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PlanValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PlanValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PlanValue Attribute Value",
				"While creating a PlanValue value, an extra attribute value was detected. "+
					"A PlanValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PlanValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPlanValueUnknown(), diags
	}

	commitmentIntervalAttribute, ok := attributes["commitment_interval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_interval is missing from object`)

		return NewPlanValueUnknown(), diags
	}

	commitmentIntervalVal, ok := commitmentIntervalAttribute.(CommitmentIntervalValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_interval expected to be CommitmentIntervalValue, was: %T`, commitmentIntervalAttribute))
	}

	isCommitmentPlanAttribute, ok := attributes["is_commitment_plan"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`is_commitment_plan is missing from object`)

		return NewPlanValueUnknown(), diags
	}

	isCommitmentPlanVal, ok := isCommitmentPlanAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`is_commitment_plan expected to be basetypes.BoolValue, was: %T`, isCommitmentPlanAttribute))
	}

	planNameAttribute, ok := attributes["plan_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_name is missing from object`)

		return NewPlanValueUnknown(), diags
	}

	planNameVal, ok := planNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_name expected to be basetypes.StringValue, was: %T`, planNameAttribute))
	}

	if diags.HasError() {
		return NewPlanValueUnknown(), diags
	}

	return PlanValue{
		CommitmentInterval: commitmentIntervalVal,
		IsCommitmentPlan:   isCommitmentPlanVal,
		PlanName:           planNameVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewPlanValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PlanValue {
	object, diags := NewPlanValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPlanValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PlanType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPlanValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPlanValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPlanValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPlanValueMust(PlanValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PlanType) ValueType(ctx context.Context) attr.Value {
	return PlanValue{}
}

var _ basetypes.ObjectValuable = PlanValue{}

type PlanValue struct {
	CommitmentInterval CommitmentIntervalValue `tfsdk:"commitment_interval"`
	IsCommitmentPlan   basetypes.BoolValue     `tfsdk:"is_commitment_plan"`
	PlanName           basetypes.StringValue   `tfsdk:"plan_name"`
	state              attr.ValueState
}

func (v PlanValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["commitment_interval"] = CommitmentIntervalType{
		basetypes.ObjectType{
			AttrTypes: CommitmentIntervalValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["is_commitment_plan"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["plan_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.CommitmentInterval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["commitment_interval"] = val

		val, err = v.IsCommitmentPlan.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["is_commitment_plan"] = val

		val, err = v.PlanName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plan_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PlanValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PlanValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PlanValue) String() string {
	return "PlanValue"
}

func (v PlanValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var commitmentInterval attr.Value

	{
		commitmentInterval = v.CommitmentInterval
	}

	attributeTypes := map[string]attr.Type{
		"commitment_interval": CommitmentIntervalType{
			basetypes.ObjectType{
				AttrTypes: CommitmentIntervalValue{}.AttributeTypes(ctx),
			},
		},
		"is_commitment_plan": basetypes.BoolType{},
		"plan_name":          basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"commitment_interval": commitmentInterval,
			"is_commitment_plan":  v.IsCommitmentPlan,
			"plan_name":           v.PlanName,
		})

	return objVal, diags
}

func (v PlanValue) Equal(o attr.Value) bool {
	other, ok := o.(PlanValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CommitmentInterval.Equal(other.CommitmentInterval) {
		return false
	}

	if !v.IsCommitmentPlan.Equal(other.IsCommitmentPlan) {
		return false
	}

	if !v.PlanName.Equal(other.PlanName) {
		return false
	}

	return true
}

func (v PlanValue) Type(ctx context.Context) attr.Type {
	return PlanType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PlanValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"commitment_interval": CommitmentIntervalType{
			basetypes.ObjectType{
				AttrTypes: CommitmentIntervalValue{}.AttributeTypes(ctx),
			},
		},
		"is_commitment_plan": basetypes.BoolType{},
		"plan_name":          basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CommitmentIntervalType{}

type CommitmentIntervalType struct {
	basetypes.ObjectType
}

func (t CommitmentIntervalType) Equal(o attr.Type) bool {
	other, ok := o.(CommitmentIntervalType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CommitmentIntervalType) String() string {
	return "CommitmentIntervalType"
}

func (t CommitmentIntervalType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	endTimeAttribute, ok := attributes["end_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_time is missing from object`)

		return nil, diags
	}

	endTimeVal, ok := endTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_time expected to be basetypes.Int64Value, was: %T`, endTimeAttribute))
	}

	startTimeAttribute, ok := attributes["start_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time is missing from object`)

		return nil, diags
	}

	startTimeVal, ok := startTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time expected to be basetypes.Int64Value, was: %T`, startTimeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CommitmentIntervalValue{
		EndTime:   endTimeVal,
		StartTime: startTimeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewCommitmentIntervalValueNull() CommitmentIntervalValue {
	return CommitmentIntervalValue{
		state: attr.ValueStateNull,
	}
}

func NewCommitmentIntervalValueUnknown() CommitmentIntervalValue {
	return CommitmentIntervalValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCommitmentIntervalValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CommitmentIntervalValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CommitmentIntervalValue Attribute Value",
				"While creating a CommitmentIntervalValue value, a missing attribute value was detected. "+
					"A CommitmentIntervalValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CommitmentIntervalValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CommitmentIntervalValue Attribute Type",
				"While creating a CommitmentIntervalValue value, an invalid attribute value was detected. "+
					"A CommitmentIntervalValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CommitmentIntervalValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CommitmentIntervalValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CommitmentIntervalValue Attribute Value",
				"While creating a CommitmentIntervalValue value, an extra attribute value was detected. "+
					"A CommitmentIntervalValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CommitmentIntervalValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCommitmentIntervalValueUnknown(), diags
	}

	endTimeAttribute, ok := attributes["end_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_time is missing from object`)

		return NewCommitmentIntervalValueUnknown(), diags
	}

	endTimeVal, ok := endTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_time expected to be basetypes.Int64Value, was: %T`, endTimeAttribute))
	}

	startTimeAttribute, ok := attributes["start_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time is missing from object`)

		return NewCommitmentIntervalValueUnknown(), diags
	}

	startTimeVal, ok := startTimeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time expected to be basetypes.Int64Value, was: %T`, startTimeAttribute))
	}

	if diags.HasError() {
		return NewCommitmentIntervalValueUnknown(), diags
	}

	return CommitmentIntervalValue{
		EndTime:   endTimeVal,
		StartTime: startTimeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewCommitmentIntervalValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CommitmentIntervalValue {
	object, diags := NewCommitmentIntervalValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCommitmentIntervalValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CommitmentIntervalType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCommitmentIntervalValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCommitmentIntervalValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCommitmentIntervalValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCommitmentIntervalValueMust(CommitmentIntervalValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CommitmentIntervalType) ValueType(ctx context.Context) attr.Value {
	return CommitmentIntervalValue{}
}

var _ basetypes.ObjectValuable = CommitmentIntervalValue{}

type CommitmentIntervalValue struct {
	EndTime   basetypes.Int64Value `tfsdk:"end_time"`
	StartTime basetypes.Int64Value `tfsdk:"start_time"`
	state     attr.ValueState
}

func (v CommitmentIntervalValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["end_time"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["start_time"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.EndTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_time"] = val

		val, err = v.StartTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_time"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CommitmentIntervalValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CommitmentIntervalValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CommitmentIntervalValue) String() string {
	return "CommitmentIntervalValue"
}

func (v CommitmentIntervalValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"end_time":   basetypes.Int64Type{},
		"start_time": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"end_time":   v.EndTime,
			"start_time": v.StartTime,
		})

	return objVal, diags
}

func (v CommitmentIntervalValue) Equal(o attr.Value) bool {
	other, ok := o.(CommitmentIntervalValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EndTime.Equal(other.EndTime) {
		return false
	}

	if !v.StartTime.Equal(other.StartTime) {
		return false
	}

	return true
}

func (v CommitmentIntervalValue) Type(ctx context.Context) attr.Type {
	return CommitmentIntervalType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CommitmentIntervalValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"end_time":   basetypes.Int64Type{},
		"start_time": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = RenewalSettingsType{}

type RenewalSettingsType struct {
	basetypes.ObjectType
}

func (t RenewalSettingsType) Equal(o attr.Type) bool {
	other, ok := o.(RenewalSettingsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t RenewalSettingsType) String() string {
	return "RenewalSettingsType"
}

func (t RenewalSettingsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	renewalTypeAttribute, ok := attributes["renewal_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`renewal_type is missing from object`)

		return nil, diags
	}

	renewalTypeVal, ok := renewalTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`renewal_type expected to be basetypes.StringValue, was: %T`, renewalTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return RenewalSettingsValue{
		RenewalType: renewalTypeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewRenewalSettingsValueNull() RenewalSettingsValue {
	return RenewalSettingsValue{
		state: attr.ValueStateNull,
	}
}

func NewRenewalSettingsValueUnknown() RenewalSettingsValue {
	return RenewalSettingsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewRenewalSettingsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (RenewalSettingsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing RenewalSettingsValue Attribute Value",
				"While creating a RenewalSettingsValue value, a missing attribute value was detected. "+
					"A RenewalSettingsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RenewalSettingsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid RenewalSettingsValue Attribute Type",
				"While creating a RenewalSettingsValue value, an invalid attribute value was detected. "+
					"A RenewalSettingsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("RenewalSettingsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("RenewalSettingsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra RenewalSettingsValue Attribute Value",
				"While creating a RenewalSettingsValue value, an extra attribute value was detected. "+
					"A RenewalSettingsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra RenewalSettingsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewRenewalSettingsValueUnknown(), diags
	}

	renewalTypeAttribute, ok := attributes["renewal_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`renewal_type is missing from object`)

		return NewRenewalSettingsValueUnknown(), diags
	}

	renewalTypeVal, ok := renewalTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`renewal_type expected to be basetypes.StringValue, was: %T`, renewalTypeAttribute))
	}

	if diags.HasError() {
		return NewRenewalSettingsValueUnknown(), diags
	}

	return RenewalSettingsValue{
		RenewalType: renewalTypeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewRenewalSettingsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) RenewalSettingsValue {
	object, diags := NewRenewalSettingsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewRenewalSettingsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t RenewalSettingsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewRenewalSettingsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewRenewalSettingsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewRenewalSettingsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewRenewalSettingsValueMust(RenewalSettingsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t RenewalSettingsType) ValueType(ctx context.Context) attr.Value {
	return RenewalSettingsValue{}
}

var _ basetypes.ObjectValuable = RenewalSettingsValue{}

type RenewalSettingsValue struct {
	RenewalType basetypes.StringValue `tfsdk:"renewal_type"`
	state       attr.ValueState
}

func (v RenewalSettingsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["renewal_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.RenewalType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["renewal_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v RenewalSettingsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v RenewalSettingsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v RenewalSettingsValue) String() string {
	return "RenewalSettingsValue"
}

func (v RenewalSettingsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"renewal_type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"renewal_type": v.RenewalType,
		})

	return objVal, diags
}

func (v RenewalSettingsValue) Equal(o attr.Value) bool {
	other, ok := o.(RenewalSettingsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RenewalType.Equal(other.RenewalType) {
		return false
	}

	return true
}

func (v RenewalSettingsValue) Type(ctx context.Context) attr.Type {
	return RenewalSettingsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v RenewalSettingsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"renewal_type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SeatsType{}

type SeatsType struct {
	basetypes.ObjectType
}

func (t SeatsType) Equal(o attr.Type) bool {
	other, ok := o.(SeatsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SeatsType) String() string {
	return "SeatsType"
}

func (t SeatsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	licensedNumberOfSeatsAttribute, ok := attributes["licensed_number_of_seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`licensed_number_of_seats is missing from object`)

		return nil, diags
	}

	licensedNumberOfSeatsVal, ok := licensedNumberOfSeatsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`licensed_number_of_seats expected to be basetypes.Int64Value, was: %T`, licensedNumberOfSeatsAttribute))
	}

	maximumNumberOfSeatsAttribute, ok := attributes["maximum_number_of_seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`maximum_number_of_seats is missing from object`)

		return nil, diags
	}

	maximumNumberOfSeatsVal, ok := maximumNumberOfSeatsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`maximum_number_of_seats expected to be basetypes.Int64Value, was: %T`, maximumNumberOfSeatsAttribute))
	}

	numberOfSeatsAttribute, ok := attributes["number_of_seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`number_of_seats is missing from object`)

		return nil, diags
	}

	numberOfSeatsVal, ok := numberOfSeatsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`number_of_seats expected to be basetypes.Int64Value, was: %T`, numberOfSeatsAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SeatsValue{
		LicensedNumberOfSeats: licensedNumberOfSeatsVal,
		MaximumNumberOfSeats:  maximumNumberOfSeatsVal,
		NumberOfSeats:         numberOfSeatsVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewSeatsValueNull() SeatsValue {
	return SeatsValue{
		state: attr.ValueStateNull,
	}
}

func NewSeatsValueUnknown() SeatsValue {
	return SeatsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSeatsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SeatsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SeatsValue Attribute Value",
				"While creating a SeatsValue value, a missing attribute value was detected. "+
					"A SeatsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SeatsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SeatsValue Attribute Type",
				"While creating a SeatsValue value, an invalid attribute value was detected. "+
					"A SeatsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SeatsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SeatsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SeatsValue Attribute Value",
				"While creating a SeatsValue value, an extra attribute value was detected. "+
					"A SeatsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SeatsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSeatsValueUnknown(), diags
	}

	licensedNumberOfSeatsAttribute, ok := attributes["licensed_number_of_seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`licensed_number_of_seats is missing from object`)

		return NewSeatsValueUnknown(), diags
	}

	licensedNumberOfSeatsVal, ok := licensedNumberOfSeatsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`licensed_number_of_seats expected to be basetypes.Int64Value, was: %T`, licensedNumberOfSeatsAttribute))
	}

	maximumNumberOfSeatsAttribute, ok := attributes["maximum_number_of_seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`maximum_number_of_seats is missing from object`)

		return NewSeatsValueUnknown(), diags
	}

	maximumNumberOfSeatsVal, ok := maximumNumberOfSeatsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`maximum_number_of_seats expected to be basetypes.Int64Value, was: %T`, maximumNumberOfSeatsAttribute))
	}

	numberOfSeatsAttribute, ok := attributes["number_of_seats"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`number_of_seats is missing from object`)

		return NewSeatsValueUnknown(), diags
	}

	numberOfSeatsVal, ok := numberOfSeatsAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`number_of_seats expected to be basetypes.Int64Value, was: %T`, numberOfSeatsAttribute))
	}

	if diags.HasError() {
		return NewSeatsValueUnknown(), diags
	}

	return SeatsValue{
		LicensedNumberOfSeats: licensedNumberOfSeatsVal,
		MaximumNumberOfSeats:  maximumNumberOfSeatsVal,
		NumberOfSeats:         numberOfSeatsVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewSeatsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SeatsValue {
	object, diags := NewSeatsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSeatsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SeatsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSeatsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSeatsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSeatsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSeatsValueMust(SeatsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SeatsType) ValueType(ctx context.Context) attr.Value {
	return SeatsValue{}
}

var _ basetypes.ObjectValuable = SeatsValue{}

type SeatsValue struct {
	LicensedNumberOfSeats basetypes.Int64Value `tfsdk:"licensed_number_of_seats"`
	MaximumNumberOfSeats  basetypes.Int64Value `tfsdk:"maximum_number_of_seats"`
	NumberOfSeats         basetypes.Int64Value `tfsdk:"number_of_seats"`
	state                 attr.ValueState
}

func (v SeatsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["licensed_number_of_seats"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["maximum_number_of_seats"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["number_of_seats"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.LicensedNumberOfSeats.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["licensed_number_of_seats"] = val

		val, err = v.MaximumNumberOfSeats.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["maximum_number_of_seats"] = val

		val, err = v.NumberOfSeats.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["number_of_seats"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SeatsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SeatsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SeatsValue) String() string {
	return "SeatsValue"
}

func (v SeatsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"licensed_number_of_seats": basetypes.Int64Type{},
		"maximum_number_of_seats":  basetypes.Int64Type{},
		"number_of_seats":          basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"licensed_number_of_seats": v.LicensedNumberOfSeats,
			"maximum_number_of_seats":  v.MaximumNumberOfSeats,
			"number_of_seats":          v.NumberOfSeats,
		})

	return objVal, diags
}

func (v SeatsValue) Equal(o attr.Value) bool {
	other, ok := o.(SeatsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.LicensedNumberOfSeats.Equal(other.LicensedNumberOfSeats) {
		return false
	}

	if !v.MaximumNumberOfSeats.Equal(other.MaximumNumberOfSeats) {
		return false
	}

	if !v.NumberOfSeats.Equal(other.NumberOfSeats) {
		return false
	}

	return true
}

func (v SeatsValue) Type(ctx context.Context) attr.Type {
	return SeatsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SeatsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"licensed_number_of_seats": basetypes.Int64Type{},
		"maximum_number_of_seats":  basetypes.Int64Type{},
		"number_of_seats":          basetypes.Int64Type{},
	}
}
