// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_support_request

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SupportRequestDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.Int64Attribute{
				Computed:            true,
				Description:         "The time when this ticket was created, in milliseconds since the epoch.",
				MarkdownDescription: "The time when this ticket was created, in milliseconds since the epoch.",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The body of the initial ticket message.",
				MarkdownDescription: "The body of the initial ticket message.",
			},
			"id": schema.Int64Attribute{
				Computed:            true,
				Description:         "Ticket ID.",
				MarkdownDescription: "Ticket ID.",
			},
			"is_public": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the ticket is public.",
				MarkdownDescription: "Whether the ticket is public.",
			},
			"platform": schema.StringAttribute{
				Computed:            true,
				Description:         "Platform of the ticket.",
				MarkdownDescription: "Platform of the ticket.",
			},
			"product": schema.StringAttribute{
				Computed:            true,
				Description:         "Ticket product.",
				MarkdownDescription: "Ticket product.",
			},
			"requester": schema.StringAttribute{
				Computed:            true,
				Description:         "Email address of the ticket requester.",
				MarkdownDescription: "Email address of the ticket requester.",
			},
			"severity": schema.StringAttribute{
				Computed:            true,
				Description:         "Ticket severity.",
				MarkdownDescription: "Ticket severity.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Ticket status.",
				MarkdownDescription: "Ticket status.",
			},
			"subject": schema.StringAttribute{
				Computed:            true,
				Description:         "The subject of the ticket.",
				MarkdownDescription: "The subject of the ticket.",
			},
			"ticket_id": schema.Int64Attribute{
				Required:            true,
				Description:         "The unique identifier of the support request.",
				MarkdownDescription: "The unique identifier of the support request.",
			},
			"update_time": schema.Int64Attribute{
				Computed:            true,
				Description:         "The time when this ticket was last updated, in milliseconds since the epoch.",
				MarkdownDescription: "The time when this ticket was last updated, in milliseconds since the epoch.",
			},
			"url_ui": schema.StringAttribute{
				Computed:            true,
				Description:         "Link to the ticket in DoiT console.",
				MarkdownDescription: "Link to the ticket in DoiT console.",
			},
		},
		Description:         "Create and manage support tickets with DoiT.",
		MarkdownDescription: "Create and manage support tickets with DoiT.",
	}
}

type SupportRequestModel struct {
	CreateTime  types.Int64  `tfsdk:"create_time"`
	Description types.String `tfsdk:"description"`
	Id          types.Int64  `tfsdk:"id"`
	IsPublic    types.Bool   `tfsdk:"is_public"`
	Platform    types.String `tfsdk:"platform"`
	Product     types.String `tfsdk:"product"`
	Requester   types.String `tfsdk:"requester"`
	Severity    types.String `tfsdk:"severity"`
	Status      types.String `tfsdk:"status"`
	Subject     types.String `tfsdk:"subject"`
	TicketId    types.Int64  `tfsdk:"ticket_id"`
	UpdateTime  types.Int64  `tfsdk:"update_time"`
	UrlUi       types.String `tfsdk:"url_ui"`
}
