// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_folder

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func FolderDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Folder description.",
				MarkdownDescription: "Folder description.",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Folder ID.",
				MarkdownDescription: "Folder ID.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Folder name.",
				MarkdownDescription: "Folder name.",
			},
			"parent_folder_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Identifier of the parent folder. Set to \"root\" if the folder is at the top level.",
				MarkdownDescription: "Identifier of the parent folder. Set to \"root\" if the folder is at the top level.",
			},
		},
		Description:         "Organize Cloud Analytics resources (reports, allocations) into folders.",
		MarkdownDescription: "Organize Cloud Analytics resources (reports, allocations) into folders.",
	}
}

type FolderModel struct {
	Description    types.String `tfsdk:"description"`
	Id             types.String `tfsdk:"id"`
	Name           types.String `tfsdk:"name"`
	ParentFolderId types.String `tfsdk:"parent_folder_id"`
}
