// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_service_account_token

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServiceAccountTokenDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the token was created. `null` only on a dry-run create.",
				MarkdownDescription: "When the token was created. `null` only on a dry-run create.",
			},
			"customer_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the customer whose service account the token belongs to.",
				MarkdownDescription: "ID of the customer whose service account the token belongs to.",
			},
			"expires_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the token stops authenticating. `null` when it does not expire.",
				MarkdownDescription: "When the token stops authenticating. `null` when it does not expire.",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "API token ID, as returned in the id field by the token list and create operations.",
				MarkdownDescription: "API token ID, as returned in the id field by the token list and create operations.",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"last_used_time": schema.StringAttribute{
				Computed:            true,
				Description:         "When the token last authenticated a request. `null` until it is first used.",
				MarkdownDescription: "When the token last authenticated a request. `null` until it is first used.",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Name, unique among the service account's tokens.",
				MarkdownDescription: "Name, unique among the service account's tokens.",
			},
			"service_account_id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the service account that owns the token, as returned in the id field by the service account list and create operations.",
				MarkdownDescription: "ID of the service account that owns the token, as returned in the id field by the service account list and create operations.",
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"state": schema.StringAttribute{
				Computed:            true,
				Description:         "The token's stored state: `active` while it is enabled, `disabled` once it has been turned off. This is not a liveness signal — a token whose `expiresTime` has passed stops authenticating but keeps the state it was stored with, so `active` here does not by itself mean the token still works; compare `expiresTime`. Only these two values can be set.",
				MarkdownDescription: "The token's stored state: `active` while it is enabled, `disabled` once it has been turned off. This is not a liveness signal — a token whose `expiresTime` has passed stops authenticating but keeps the state it was stored with, so `active` here does not by itself mean the token still works; compare `expiresTime`. Only these two values can be set.",
			},
		},
		Description:         "Manage non-human identities whose API tokens call the DoiT API with a fixed set of permissions.",
		MarkdownDescription: "Manage non-human identities whose API tokens call the DoiT API with a fixed set of permissions.",
	}
}

type ServiceAccountTokenModel struct {
	CreateTime       types.String `tfsdk:"create_time"`
	CustomerId       types.String `tfsdk:"customer_id"`
	ExpiresTime      types.String `tfsdk:"expires_time"`
	Id               types.String `tfsdk:"id"`
	LastUsedTime     types.String `tfsdk:"last_used_time"`
	Name             types.String `tfsdk:"name"`
	ServiceAccountId types.String `tfsdk:"service_account_id"`
	State            types.String `tfsdk:"state"`
}
