// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_cloudflow_flow

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func CloudflowFlowResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"create_time": schema.StringAttribute{
				Computed:            true,
				Description:         "ISO 8601 timestamp (UTC) when the flow was created. `null` on dry-run create.",
				MarkdownDescription: "ISO 8601 timestamp (UTC) when the flow was created. `null` on dry-run create.",
			},
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Human-readable description.",
				MarkdownDescription: "Human-readable description.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(2000),
				},
			},
			"etag": schema.StringAttribute{
				Computed:            true,
				Description:         "Strong ETag for this resource version. Pass as `If-Match` on subsequent mutations.\n`null` on dry-run create responses.\n",
				MarkdownDescription: "Strong ETag for this resource version. Pass as `If-Match` on subsequent mutations.\n`null` on dry-run create responses.\n",
			},
			"first_node_id": schema.StringAttribute{
				Computed:            true,
				Description:         "ID of the trigger (first) node. `null` if no trigger node has been set.",
				MarkdownDescription: "ID of the trigger (first) node. `null` if no trigger node has been set.",
			},
			"flow_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Flow ID",
				MarkdownDescription: "Flow ID",
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "Server-assigned unique identifier. `null` on dry-run create responses\n(no resource was persisted).\n",
				MarkdownDescription: "Server-assigned unique identifier. `null` on dry-run create responses\n(no resource was persisted).\n",
			},
			"instructions": schema.StringAttribute{
				Computed:            true,
				Description:         "Operator instructions or notes attached to the flow.",
				MarkdownDescription: "Operator instructions or notes attached to the flow.",
			},
			"last_executed_time": schema.StringAttribute{
				Computed:            true,
				Description:         "ISO 8601 timestamp (UTC) of the most recent execution. `null` if never executed.",
				MarkdownDescription: "ISO 8601 timestamp (UTC) of the most recent execution. `null` if never executed.",
			},
			"last_execution_status": schema.StringAttribute{
				Computed:            true,
				Description:         "Status string of the most recent execution. `null` if never executed.",
				MarkdownDescription: "Status string of the most recent execution. `null` if never executed.",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "Display name for the new flow.",
				MarkdownDescription: "Display name for the new flow.",
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 200),
				},
			},
			"nodes": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"action_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Identifier of the specific operation this node performs (e.g. AWS service action).",
							MarkdownDescription: "Identifier of the specific operation this node performs (e.g. AWS service action).",
						},
						"app_key": schema.StringAttribute{
							Computed:            true,
							Description:         "Identifier of the integration or application this node belongs to.",
							MarkdownDescription: "Identifier of the integration or application this node belongs to.",
						},
						"approval": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"message": schema.StringAttribute{
									Computed:            true,
									Description:         "Approval request message shown to the recipient.",
									MarkdownDescription: "Approval request message shown to the recipient.",
								},
								"recipient_email": schema.StringAttribute{
									Computed:            true,
									Description:         "Email address of the approval recipient.",
									MarkdownDescription: "Email address of the approval recipient.",
								},
								"reject_approval_after_time": schema.BoolAttribute{
									Computed:            true,
									Description:         "Whether the approval auto-rejects if not acted on within the time window.",
									MarkdownDescription: "Whether the approval auto-rejects if not acted on within the time window.",
								},
								"reject_time_unit": schema.StringAttribute{
									Computed:            true,
									Description:         "Time unit for the auto-rejection window.",
									MarkdownDescription: "Time unit for the auto-rejection window.",
								},
								"reject_time_value": schema.Int64Attribute{
									Computed:            true,
									Description:         "Number of time units before auto-rejection.",
									MarkdownDescription: "Number of time units before auto-rejection.",
								},
								"required": schema.BoolAttribute{
									Computed:            true,
									Description:         "Whether approval is required before the node can proceed.",
									MarkdownDescription: "Whether approval is required before the node can proceed.",
								},
							},
							CustomType: ApprovalType{
								ObjectType: types.ObjectType{
									AttrTypes: ApprovalValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "Optional human approval gate. `null` if no approval is required.",
							MarkdownDescription: "Optional human approval gate. `null` if no approval is required.",
						},
						"create_time": schema.StringAttribute{
							Computed:            true,
							Description:         "ISO 8601 (UTC) creation timestamp. `null` on dry-run create.",
							MarkdownDescription: "ISO 8601 (UTC) creation timestamp. `null` on dry-run create.",
						},
						"description": schema.StringAttribute{
							Computed:            true,
							Description:         "Human-readable description.",
							MarkdownDescription: "Human-readable description.",
						},
						"disabled": schema.BoolAttribute{
							Computed:            true,
							Description:         "When `true` this node is skipped during flow execution.",
							MarkdownDescription: "When `true` this node is skipped during flow execution.",
						},
						"error_messages": schema.MapAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "Map of field-path → error message for nodes in the `error` status.",
							MarkdownDescription: "Map of field-path → error message for nodes in the `error` status.",
						},
						"etag": schema.StringAttribute{
							Computed:            true,
							Description:         "Strong ETag for this node version. `null` on dry-run create.",
							MarkdownDescription: "Strong ETag for this node version. `null` on dry-run create.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "Server-assigned unique identifier. `null` on dry-run create responses.",
							MarkdownDescription: "Server-assigned unique identifier. `null` on dry-run create responses.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Display name.",
							MarkdownDescription: "Display name.",
						},
						"parameters": schema.StringAttribute{
							CustomType:          jsontypes.NormalizedType{},
							Computed:            true,
							Description:         "Node-specific configuration. The concrete schema depends on `type`. See the\nCloudFlow node type documentation for full parameter shapes. Key parameter\nschemas are also defined in the internal spec at\n`services/cloudflow/api/openapi/spec.yaml` (NodeParameters and variants).\n. Value is JSON-encoded.",
							MarkdownDescription: "Node-specific configuration. The concrete schema depends on `type`. See the\nCloudFlow node type documentation for full parameter shapes. Key parameter\nschemas are also defined in the internal spec at\n`services/cloudflow/api/openapi/spec.yaml` (NodeParameters and variants).\n. Value is JSON-encoded.",
						},
						"status": schema.StringAttribute{
							Computed:            true,
							Description:         "Validation state. `null` on dry-run create responses.",
							MarkdownDescription: "Validation state. `null` on dry-run create responses.",
						},
						"transitions": schema.ListNestedAttribute{
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"label": schema.StringAttribute{
										Computed:            true,
										Description:         "Optional display label shown on the canvas edge.",
										MarkdownDescription: "Optional display label shown on the canvas edge.",
									},
									"target_node_id": schema.StringAttribute{
										Computed:            true,
										Description:         "ID of the target (child) node.",
										MarkdownDescription: "ID of the target (child) node.",
									},
								},
								CustomType: TransitionsType{
									ObjectType: types.ObjectType{
										AttrTypes: TransitionsValue{}.AttributeTypes(ctx),
									},
								},
							},
							Computed:            true,
							Description:         "Directed edges to child nodes.",
							MarkdownDescription: "Directed edges to child nodes.",
						},
						"type": schema.StringAttribute{
							Computed:            true,
							Description:         "Discriminator that identifies a node's role and determines the shape of its\n`parameters` field.\n",
							MarkdownDescription: "Discriminator that identifies a node's role and determines the shape of its\n`parameters` field.\n",
						},
						"update_time": schema.StringAttribute{
							Computed:            true,
							Description:         "ISO 8601 (UTC) last-modified timestamp. `null` if never modified.",
							MarkdownDescription: "ISO 8601 (UTC) last-modified timestamp. `null` if never modified.",
						},
					},
					CustomType: NodesType{
						ObjectType: types.ObjectType{
							AttrTypes: NodesValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Embedded nodes. Populated by the `update-batch` response and by operations that\nreturn the full flow with nodes inline. Not present on standard list responses.\n",
				MarkdownDescription: "Embedded nodes. Populated by the `update-batch` response and by operations that\nreturn the full flow with nodes inline. Not present on standard list responses.\n",
			},
			"published": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether the flow is currently published. Readable on every response; use\n`POST /actions/publish` and `POST /actions/unpublish` to change this value.\n",
				MarkdownDescription: "Whether the flow is currently published. Readable on every response; use\n`POST /actions/publish` and `POST /actions/unpublish` to change this value.\n",
			},
			"schedule": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"custom_frequency": schema.StringAttribute{
						Computed:            true,
						Description:         "Time unit when `frequency` is `Custom`. One of: `Hour`, `Day`, `Week`, `Month`.\n",
						MarkdownDescription: "Time unit when `frequency` is `Custom`. One of: `Hour`, `Day`, `Week`, `Month`.\n",
					},
					"custom_frequency_amount": schema.Int64Attribute{
						Computed:            true,
						Description:         "Number of `customFrequency` units between runs. Required when `frequency` is `Custom`.",
						MarkdownDescription: "Number of `customFrequency` units between runs. Required when `frequency` is `Custom`.",
					},
					"frequency": schema.StringAttribute{
						Computed:            true,
						Description:         "Schedule cadence preset. One of: `Daily`, `Weekly`, `Monthly`, `Do not repeat`, `Custom`.\n",
						MarkdownDescription: "Schedule cadence preset. One of: `Daily`, `Weekly`, `Monthly`, `Do not repeat`, `Custom`.\n",
					},
					"next_run": schema.StringAttribute{
						Computed:            true,
						Description:         "ISO 8601 (UTC) timestamp of the next scheduled run. `null` if not scheduled or paused.",
						MarkdownDescription: "ISO 8601 (UTC) timestamp of the next scheduled run. `null` if not scheduled or paused.",
					},
					"scheduled": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether scheduling is currently enabled.",
						MarkdownDescription: "Whether scheduling is currently enabled.",
					},
				},
				CustomType: ScheduleType{
					ObjectType: types.ObjectType{
						AttrTypes: ScheduleValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Schedule configuration. `null` if the flow does not have scheduling configured.",
				MarkdownDescription: "Schedule configuration. `null` if the flow does not have scheduling configured.",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "Lifecycle state. `null` on dry-run create responses.",
				MarkdownDescription: "Lifecycle state. `null` on dry-run create responses.",
			},
			"template_id": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "ID of a template (blueprint) to initialise the flow from. When present the\nnew flow inherits the template's node graph and structure. The template itself\nis not modified.\n",
				MarkdownDescription: "ID of a template (blueprint) to initialise the flow from. When present the\nnew flow inherits the template's node graph and structure. The template itself\nis not modified.\n",
			},
			"trigger_type": schema.StringAttribute{
				Computed:            true,
				Description:         "Node type of the trigger node. `null` if no trigger node has been set.\nOne of the `ExternalNodeType` trigger variants: `triggerNode`, `manualTrigger`,\n`webhookTrigger`, `systemEventTrigger`, `scheduleTrigger`.\n",
				MarkdownDescription: "Node type of the trigger node. `null` if no trigger node has been set.\nOne of the `ExternalNodeType` trigger variants: `triggerNode`, `manualTrigger`,\n`webhookTrigger`, `systemEventTrigger`, `scheduleTrigger`.\n",
			},
			"update_time": schema.StringAttribute{
				Computed:            true,
				Description:         "ISO 8601 timestamp (UTC) of the last modification. `null` if never modified or on dry-run.",
				MarkdownDescription: "ISO 8601 timestamp (UTC) of the last modification. `null` if never modified or on dry-run.",
			},
		},
	}
}

type CloudflowFlowModel struct {
	CreateTime          types.String  `tfsdk:"create_time"`
	Description         types.String  `tfsdk:"description"`
	Etag                types.String  `tfsdk:"etag"`
	FirstNodeId         types.String  `tfsdk:"first_node_id"`
	FlowId              types.String  `tfsdk:"flow_id"`
	Id                  types.String  `tfsdk:"id"`
	Instructions        types.String  `tfsdk:"instructions"`
	LastExecutedTime    types.String  `tfsdk:"last_executed_time"`
	LastExecutionStatus types.String  `tfsdk:"last_execution_status"`
	Name                types.String  `tfsdk:"name"`
	Nodes               types.List    `tfsdk:"nodes"`
	Published           types.Bool    `tfsdk:"published"`
	Schedule            ScheduleValue `tfsdk:"schedule"`
	Status              types.String  `tfsdk:"status"`
	TemplateId          types.String  `tfsdk:"template_id"`
	TriggerType         types.String  `tfsdk:"trigger_type"`
	UpdateTime          types.String  `tfsdk:"update_time"`
}

var _ basetypes.ObjectTypable = NodesType{}

type NodesType struct {
	basetypes.ObjectType
}

func (t NodesType) Equal(o attr.Type) bool {
	other, ok := o.(NodesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t NodesType) String() string {
	return "NodesType"
}

func (t NodesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	actionIdAttribute, ok := attributes["action_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action_id is missing from object`)

		return nil, diags
	}

	actionIdVal, ok := actionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action_id expected to be basetypes.StringValue, was: %T`, actionIdAttribute))
	}

	appKeyAttribute, ok := attributes["app_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`app_key is missing from object`)

		return nil, diags
	}

	appKeyVal, ok := appKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`app_key expected to be basetypes.StringValue, was: %T`, appKeyAttribute))
	}

	approvalAttribute, ok := attributes["approval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`approval is missing from object`)

		return nil, diags
	}

	approvalVal, ok := approvalAttribute.(ApprovalValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`approval expected to be ApprovalValue, was: %T`, approvalAttribute))
	}

	createTimeAttribute, ok := attributes["create_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create_time is missing from object`)

		return nil, diags
	}

	createTimeVal, ok := createTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create_time expected to be basetypes.StringValue, was: %T`, createTimeAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	disabledAttribute, ok := attributes["disabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disabled is missing from object`)

		return nil, diags
	}

	disabledVal, ok := disabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disabled expected to be basetypes.BoolValue, was: %T`, disabledAttribute))
	}

	errorMessagesAttribute, ok := attributes["error_messages"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`error_messages is missing from object`)

		return nil, diags
	}

	errorMessagesVal, ok := errorMessagesAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`error_messages expected to be basetypes.MapValue, was: %T`, errorMessagesAttribute))
	}

	etagAttribute, ok := attributes["etag"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`etag is missing from object`)

		return nil, diags
	}

	etagVal, ok := etagAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`etag expected to be basetypes.StringValue, was: %T`, etagAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	parametersAttribute, ok := attributes["parameters"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parameters is missing from object`)

		return nil, diags
	}

	parametersVal, ok := parametersAttribute.(jsontypes.Normalized)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parameters expected to be jsontypes.Normalized, was: %T`, parametersAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	transitionsAttribute, ok := attributes["transitions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`transitions is missing from object`)

		return nil, diags
	}

	transitionsVal, ok := transitionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`transitions expected to be basetypes.ListValue, was: %T`, transitionsAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	updateTimeAttribute, ok := attributes["update_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update_time is missing from object`)

		return nil, diags
	}

	updateTimeVal, ok := updateTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update_time expected to be basetypes.StringValue, was: %T`, updateTimeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return NodesValue{
		ActionId:      actionIdVal,
		AppKey:        appKeyVal,
		Approval:      approvalVal,
		CreateTime:    createTimeVal,
		Description:   descriptionVal,
		Disabled:      disabledVal,
		ErrorMessages: errorMessagesVal,
		Etag:          etagVal,
		Id:            idVal,
		Name:          nameVal,
		Parameters:    parametersVal,
		Status:        statusVal,
		Transitions:   transitionsVal,
		NodesType:     typeVal,
		UpdateTime:    updateTimeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewNodesValueNull() NodesValue {
	return NodesValue{
		state: attr.ValueStateNull,
	}
}

func NewNodesValueUnknown() NodesValue {
	return NodesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewNodesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (NodesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing NodesValue Attribute Value",
				"While creating a NodesValue value, a missing attribute value was detected. "+
					"A NodesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid NodesValue Attribute Type",
				"While creating a NodesValue value, an invalid attribute value was detected. "+
					"A NodesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("NodesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("NodesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra NodesValue Attribute Value",
				"While creating a NodesValue value, an extra attribute value was detected. "+
					"A NodesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra NodesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewNodesValueUnknown(), diags
	}

	actionIdAttribute, ok := attributes["action_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`action_id is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	actionIdVal, ok := actionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`action_id expected to be basetypes.StringValue, was: %T`, actionIdAttribute))
	}

	appKeyAttribute, ok := attributes["app_key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`app_key is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	appKeyVal, ok := appKeyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`app_key expected to be basetypes.StringValue, was: %T`, appKeyAttribute))
	}

	approvalAttribute, ok := attributes["approval"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`approval is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	approvalVal, ok := approvalAttribute.(ApprovalValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`approval expected to be ApprovalValue, was: %T`, approvalAttribute))
	}

	createTimeAttribute, ok := attributes["create_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`create_time is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	createTimeVal, ok := createTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`create_time expected to be basetypes.StringValue, was: %T`, createTimeAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	disabledAttribute, ok := attributes["disabled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disabled is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	disabledVal, ok := disabledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disabled expected to be basetypes.BoolValue, was: %T`, disabledAttribute))
	}

	errorMessagesAttribute, ok := attributes["error_messages"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`error_messages is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	errorMessagesVal, ok := errorMessagesAttribute.(basetypes.MapValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`error_messages expected to be basetypes.MapValue, was: %T`, errorMessagesAttribute))
	}

	etagAttribute, ok := attributes["etag"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`etag is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	etagVal, ok := etagAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`etag expected to be basetypes.StringValue, was: %T`, etagAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	parametersAttribute, ok := attributes["parameters"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`parameters is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	parametersVal, ok := parametersAttribute.(jsontypes.Normalized)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`parameters expected to be jsontypes.Normalized, was: %T`, parametersAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	transitionsAttribute, ok := attributes["transitions"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`transitions is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	transitionsVal, ok := transitionsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`transitions expected to be basetypes.ListValue, was: %T`, transitionsAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	updateTimeAttribute, ok := attributes["update_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`update_time is missing from object`)

		return NewNodesValueUnknown(), diags
	}

	updateTimeVal, ok := updateTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`update_time expected to be basetypes.StringValue, was: %T`, updateTimeAttribute))
	}

	if diags.HasError() {
		return NewNodesValueUnknown(), diags
	}

	return NodesValue{
		ActionId:      actionIdVal,
		AppKey:        appKeyVal,
		Approval:      approvalVal,
		CreateTime:    createTimeVal,
		Description:   descriptionVal,
		Disabled:      disabledVal,
		ErrorMessages: errorMessagesVal,
		Etag:          etagVal,
		Id:            idVal,
		Name:          nameVal,
		Parameters:    parametersVal,
		Status:        statusVal,
		Transitions:   transitionsVal,
		NodesType:     typeVal,
		UpdateTime:    updateTimeVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewNodesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) NodesValue {
	object, diags := NewNodesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewNodesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t NodesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewNodesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewNodesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewNodesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewNodesValueMust(NodesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t NodesType) ValueType(ctx context.Context) attr.Value {
	return NodesValue{}
}

var _ basetypes.ObjectValuable = NodesValue{}

type NodesValue struct {
	ActionId      basetypes.StringValue `tfsdk:"action_id"`
	AppKey        basetypes.StringValue `tfsdk:"app_key"`
	Approval      ApprovalValue         `tfsdk:"approval"`
	CreateTime    basetypes.StringValue `tfsdk:"create_time"`
	Description   basetypes.StringValue `tfsdk:"description"`
	Disabled      basetypes.BoolValue   `tfsdk:"disabled"`
	ErrorMessages basetypes.MapValue    `tfsdk:"error_messages"`
	Etag          basetypes.StringValue `tfsdk:"etag"`
	Id            basetypes.StringValue `tfsdk:"id"`
	Name          basetypes.StringValue `tfsdk:"name"`
	Parameters    jsontypes.Normalized  `tfsdk:"parameters"`
	Status        basetypes.StringValue `tfsdk:"status"`
	Transitions   basetypes.ListValue   `tfsdk:"transitions"`
	NodesType     basetypes.StringValue `tfsdk:"type"`
	UpdateTime    basetypes.StringValue `tfsdk:"update_time"`
	state         attr.ValueState
}

func (v NodesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 15)

	var val tftypes.Value
	var err error

	attrTypes["action_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["app_key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["approval"] = ApprovalType{
		basetypes.ObjectType{
			AttrTypes: ApprovalValue{}.AttributeTypes(ctx),
		},
	}.TerraformType(ctx)
	attrTypes["create_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["disabled"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["error_messages"] = basetypes.MapType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["etag"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["parameters"] = jsontypes.NormalizedType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["transitions"] = basetypes.ListType{
		ElemType: TransitionsValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["update_time"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 15)

		val, err = v.ActionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["action_id"] = val

		val, err = v.AppKey.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["app_key"] = val

		val, err = v.Approval.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["approval"] = val

		val, err = v.CreateTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["create_time"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Disabled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["disabled"] = val

		val, err = v.ErrorMessages.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["error_messages"] = val

		val, err = v.Etag.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["etag"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Parameters.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["parameters"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.Transitions.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["transitions"] = val

		val, err = v.NodesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.UpdateTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["update_time"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v NodesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v NodesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v NodesValue) String() string {
	return "NodesValue"
}

func (v NodesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var approval attr.Value

	{
		approval = v.Approval
	}

	var transitions attr.Value

	{
		transitions = v.Transitions
	}

	var errorMessagesVal basetypes.MapValue
	switch {
	case v.ErrorMessages.IsUnknown():
		errorMessagesVal = types.MapUnknown(types.StringType)
	case v.ErrorMessages.IsNull():
		errorMessagesVal = types.MapNull(types.StringType)
	default:
		var d diag.Diagnostics
		errorMessagesVal, d = types.MapValue(types.StringType, v.ErrorMessages.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"action_id": basetypes.StringType{},
			"app_key":   basetypes.StringType{},
			"approval": ApprovalType{
				basetypes.ObjectType{
					AttrTypes: ApprovalValue{}.AttributeTypes(ctx),
				},
			},
			"create_time": basetypes.StringType{},
			"description": basetypes.StringType{},
			"disabled":    basetypes.BoolType{},
			"error_messages": basetypes.MapType{
				ElemType: types.StringType,
			},
			"etag":       basetypes.StringType{},
			"id":         basetypes.StringType{},
			"name":       basetypes.StringType{},
			"parameters": jsontypes.NormalizedType{},
			"status":     basetypes.StringType{},
			"transitions": basetypes.ListType{
				ElemType: TransitionsValue{}.Type(ctx),
			},
			"type":        basetypes.StringType{},
			"update_time": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"action_id": basetypes.StringType{},
		"app_key":   basetypes.StringType{},
		"approval": ApprovalType{
			basetypes.ObjectType{
				AttrTypes: ApprovalValue{}.AttributeTypes(ctx),
			},
		},
		"create_time": basetypes.StringType{},
		"description": basetypes.StringType{},
		"disabled":    basetypes.BoolType{},
		"error_messages": basetypes.MapType{
			ElemType: types.StringType,
		},
		"etag":       basetypes.StringType{},
		"id":         basetypes.StringType{},
		"name":       basetypes.StringType{},
		"parameters": jsontypes.NormalizedType{},
		"status":     basetypes.StringType{},
		"transitions": basetypes.ListType{
			ElemType: TransitionsValue{}.Type(ctx),
		},
		"type":        basetypes.StringType{},
		"update_time": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"action_id":      v.ActionId,
			"app_key":        v.AppKey,
			"approval":       approval,
			"create_time":    v.CreateTime,
			"description":    v.Description,
			"disabled":       v.Disabled,
			"error_messages": errorMessagesVal,
			"etag":           v.Etag,
			"id":             v.Id,
			"name":           v.Name,
			"parameters":     v.Parameters,
			"status":         v.Status,
			"transitions":    transitions,
			"type":           v.NodesType,
			"update_time":    v.UpdateTime,
		})

	return objVal, diags
}

func (v NodesValue) Equal(o attr.Value) bool {
	other, ok := o.(NodesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ActionId.Equal(other.ActionId) {
		return false
	}

	if !v.AppKey.Equal(other.AppKey) {
		return false
	}

	if !v.Approval.Equal(other.Approval) {
		return false
	}

	if !v.CreateTime.Equal(other.CreateTime) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Disabled.Equal(other.Disabled) {
		return false
	}

	if !v.ErrorMessages.Equal(other.ErrorMessages) {
		return false
	}

	if !v.Etag.Equal(other.Etag) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Parameters.Equal(other.Parameters) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.Transitions.Equal(other.Transitions) {
		return false
	}

	if !v.NodesType.Equal(other.NodesType) {
		return false
	}

	if !v.UpdateTime.Equal(other.UpdateTime) {
		return false
	}

	return true
}

func (v NodesValue) Type(ctx context.Context) attr.Type {
	return NodesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v NodesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"action_id": basetypes.StringType{},
		"app_key":   basetypes.StringType{},
		"approval": ApprovalType{
			basetypes.ObjectType{
				AttrTypes: ApprovalValue{}.AttributeTypes(ctx),
			},
		},
		"create_time": basetypes.StringType{},
		"description": basetypes.StringType{},
		"disabled":    basetypes.BoolType{},
		"error_messages": basetypes.MapType{
			ElemType: types.StringType,
		},
		"etag":       basetypes.StringType{},
		"id":         basetypes.StringType{},
		"name":       basetypes.StringType{},
		"parameters": jsontypes.NormalizedType{},
		"status":     basetypes.StringType{},
		"transitions": basetypes.ListType{
			ElemType: TransitionsValue{}.Type(ctx),
		},
		"type":        basetypes.StringType{},
		"update_time": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ApprovalType{}

type ApprovalType struct {
	basetypes.ObjectType
}

func (t ApprovalType) Equal(o attr.Type) bool {
	other, ok := o.(ApprovalType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ApprovalType) String() string {
	return "ApprovalType"
}

func (t ApprovalType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return nil, diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	recipientEmailAttribute, ok := attributes["recipient_email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`recipient_email is missing from object`)

		return nil, diags
	}

	recipientEmailVal, ok := recipientEmailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`recipient_email expected to be basetypes.StringValue, was: %T`, recipientEmailAttribute))
	}

	rejectApprovalAfterTimeAttribute, ok := attributes["reject_approval_after_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reject_approval_after_time is missing from object`)

		return nil, diags
	}

	rejectApprovalAfterTimeVal, ok := rejectApprovalAfterTimeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reject_approval_after_time expected to be basetypes.BoolValue, was: %T`, rejectApprovalAfterTimeAttribute))
	}

	rejectTimeUnitAttribute, ok := attributes["reject_time_unit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reject_time_unit is missing from object`)

		return nil, diags
	}

	rejectTimeUnitVal, ok := rejectTimeUnitAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reject_time_unit expected to be basetypes.StringValue, was: %T`, rejectTimeUnitAttribute))
	}

	rejectTimeValueAttribute, ok := attributes["reject_time_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reject_time_value is missing from object`)

		return nil, diags
	}

	rejectTimeValueVal, ok := rejectTimeValueAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reject_time_value expected to be basetypes.Int64Value, was: %T`, rejectTimeValueAttribute))
	}

	requiredAttribute, ok := attributes["required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`required is missing from object`)

		return nil, diags
	}

	requiredVal, ok := requiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`required expected to be basetypes.BoolValue, was: %T`, requiredAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ApprovalValue{
		Message:                 messageVal,
		RecipientEmail:          recipientEmailVal,
		RejectApprovalAfterTime: rejectApprovalAfterTimeVal,
		RejectTimeUnit:          rejectTimeUnitVal,
		RejectTimeValue:         rejectTimeValueVal,
		Required:                requiredVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewApprovalValueNull() ApprovalValue {
	return ApprovalValue{
		state: attr.ValueStateNull,
	}
}

func NewApprovalValueUnknown() ApprovalValue {
	return ApprovalValue{
		state: attr.ValueStateUnknown,
	}
}

func NewApprovalValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ApprovalValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ApprovalValue Attribute Value",
				"While creating a ApprovalValue value, a missing attribute value was detected. "+
					"A ApprovalValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ApprovalValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ApprovalValue Attribute Type",
				"While creating a ApprovalValue value, an invalid attribute value was detected. "+
					"A ApprovalValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ApprovalValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ApprovalValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ApprovalValue Attribute Value",
				"While creating a ApprovalValue value, an extra attribute value was detected. "+
					"A ApprovalValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ApprovalValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewApprovalValueUnknown(), diags
	}

	messageAttribute, ok := attributes["message"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`message is missing from object`)

		return NewApprovalValueUnknown(), diags
	}

	messageVal, ok := messageAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`message expected to be basetypes.StringValue, was: %T`, messageAttribute))
	}

	recipientEmailAttribute, ok := attributes["recipient_email"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`recipient_email is missing from object`)

		return NewApprovalValueUnknown(), diags
	}

	recipientEmailVal, ok := recipientEmailAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`recipient_email expected to be basetypes.StringValue, was: %T`, recipientEmailAttribute))
	}

	rejectApprovalAfterTimeAttribute, ok := attributes["reject_approval_after_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reject_approval_after_time is missing from object`)

		return NewApprovalValueUnknown(), diags
	}

	rejectApprovalAfterTimeVal, ok := rejectApprovalAfterTimeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reject_approval_after_time expected to be basetypes.BoolValue, was: %T`, rejectApprovalAfterTimeAttribute))
	}

	rejectTimeUnitAttribute, ok := attributes["reject_time_unit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reject_time_unit is missing from object`)

		return NewApprovalValueUnknown(), diags
	}

	rejectTimeUnitVal, ok := rejectTimeUnitAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reject_time_unit expected to be basetypes.StringValue, was: %T`, rejectTimeUnitAttribute))
	}

	rejectTimeValueAttribute, ok := attributes["reject_time_value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`reject_time_value is missing from object`)

		return NewApprovalValueUnknown(), diags
	}

	rejectTimeValueVal, ok := rejectTimeValueAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`reject_time_value expected to be basetypes.Int64Value, was: %T`, rejectTimeValueAttribute))
	}

	requiredAttribute, ok := attributes["required"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`required is missing from object`)

		return NewApprovalValueUnknown(), diags
	}

	requiredVal, ok := requiredAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`required expected to be basetypes.BoolValue, was: %T`, requiredAttribute))
	}

	if diags.HasError() {
		return NewApprovalValueUnknown(), diags
	}

	return ApprovalValue{
		Message:                 messageVal,
		RecipientEmail:          recipientEmailVal,
		RejectApprovalAfterTime: rejectApprovalAfterTimeVal,
		RejectTimeUnit:          rejectTimeUnitVal,
		RejectTimeValue:         rejectTimeValueVal,
		Required:                requiredVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewApprovalValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ApprovalValue {
	object, diags := NewApprovalValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewApprovalValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ApprovalType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewApprovalValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewApprovalValueUnknown(), nil
	}

	if in.IsNull() {
		return NewApprovalValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewApprovalValueMust(ApprovalValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ApprovalType) ValueType(ctx context.Context) attr.Value {
	return ApprovalValue{}
}

var _ basetypes.ObjectValuable = ApprovalValue{}

type ApprovalValue struct {
	Message                 basetypes.StringValue `tfsdk:"message"`
	RecipientEmail          basetypes.StringValue `tfsdk:"recipient_email"`
	RejectApprovalAfterTime basetypes.BoolValue   `tfsdk:"reject_approval_after_time"`
	RejectTimeUnit          basetypes.StringValue `tfsdk:"reject_time_unit"`
	RejectTimeValue         basetypes.Int64Value  `tfsdk:"reject_time_value"`
	Required                basetypes.BoolValue   `tfsdk:"required"`
	state                   attr.ValueState
}

func (v ApprovalValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 6)

	var val tftypes.Value
	var err error

	attrTypes["message"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["recipient_email"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["reject_approval_after_time"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["reject_time_unit"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["reject_time_value"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["required"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 6)

		val, err = v.Message.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["message"] = val

		val, err = v.RecipientEmail.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["recipient_email"] = val

		val, err = v.RejectApprovalAfterTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["reject_approval_after_time"] = val

		val, err = v.RejectTimeUnit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["reject_time_unit"] = val

		val, err = v.RejectTimeValue.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["reject_time_value"] = val

		val, err = v.Required.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["required"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ApprovalValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ApprovalValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ApprovalValue) String() string {
	return "ApprovalValue"
}

func (v ApprovalValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"message":                    basetypes.StringType{},
		"recipient_email":            basetypes.StringType{},
		"reject_approval_after_time": basetypes.BoolType{},
		"reject_time_unit":           basetypes.StringType{},
		"reject_time_value":          basetypes.Int64Type{},
		"required":                   basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"message":                    v.Message,
			"recipient_email":            v.RecipientEmail,
			"reject_approval_after_time": v.RejectApprovalAfterTime,
			"reject_time_unit":           v.RejectTimeUnit,
			"reject_time_value":          v.RejectTimeValue,
			"required":                   v.Required,
		})

	return objVal, diags
}

func (v ApprovalValue) Equal(o attr.Value) bool {
	other, ok := o.(ApprovalValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Message.Equal(other.Message) {
		return false
	}

	if !v.RecipientEmail.Equal(other.RecipientEmail) {
		return false
	}

	if !v.RejectApprovalAfterTime.Equal(other.RejectApprovalAfterTime) {
		return false
	}

	if !v.RejectTimeUnit.Equal(other.RejectTimeUnit) {
		return false
	}

	if !v.RejectTimeValue.Equal(other.RejectTimeValue) {
		return false
	}

	if !v.Required.Equal(other.Required) {
		return false
	}

	return true
}

func (v ApprovalValue) Type(ctx context.Context) attr.Type {
	return ApprovalType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ApprovalValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"message":                    basetypes.StringType{},
		"recipient_email":            basetypes.StringType{},
		"reject_approval_after_time": basetypes.BoolType{},
		"reject_time_unit":           basetypes.StringType{},
		"reject_time_value":          basetypes.Int64Type{},
		"required":                   basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = TransitionsType{}

type TransitionsType struct {
	basetypes.ObjectType
}

func (t TransitionsType) Equal(o attr.Type) bool {
	other, ok := o.(TransitionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TransitionsType) String() string {
	return "TransitionsType"
}

func (t TransitionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	labelAttribute, ok := attributes["label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`label is missing from object`)

		return nil, diags
	}

	labelVal, ok := labelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`label expected to be basetypes.StringValue, was: %T`, labelAttribute))
	}

	targetNodeIdAttribute, ok := attributes["target_node_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`target_node_id is missing from object`)

		return nil, diags
	}

	targetNodeIdVal, ok := targetNodeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`target_node_id expected to be basetypes.StringValue, was: %T`, targetNodeIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TransitionsValue{
		Label:        labelVal,
		TargetNodeId: targetNodeIdVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewTransitionsValueNull() TransitionsValue {
	return TransitionsValue{
		state: attr.ValueStateNull,
	}
}

func NewTransitionsValueUnknown() TransitionsValue {
	return TransitionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTransitionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TransitionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TransitionsValue Attribute Value",
				"While creating a TransitionsValue value, a missing attribute value was detected. "+
					"A TransitionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TransitionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TransitionsValue Attribute Type",
				"While creating a TransitionsValue value, an invalid attribute value was detected. "+
					"A TransitionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TransitionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TransitionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TransitionsValue Attribute Value",
				"While creating a TransitionsValue value, an extra attribute value was detected. "+
					"A TransitionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TransitionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTransitionsValueUnknown(), diags
	}

	labelAttribute, ok := attributes["label"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`label is missing from object`)

		return NewTransitionsValueUnknown(), diags
	}

	labelVal, ok := labelAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`label expected to be basetypes.StringValue, was: %T`, labelAttribute))
	}

	targetNodeIdAttribute, ok := attributes["target_node_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`target_node_id is missing from object`)

		return NewTransitionsValueUnknown(), diags
	}

	targetNodeIdVal, ok := targetNodeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`target_node_id expected to be basetypes.StringValue, was: %T`, targetNodeIdAttribute))
	}

	if diags.HasError() {
		return NewTransitionsValueUnknown(), diags
	}

	return TransitionsValue{
		Label:        labelVal,
		TargetNodeId: targetNodeIdVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewTransitionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TransitionsValue {
	object, diags := NewTransitionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTransitionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TransitionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTransitionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTransitionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTransitionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTransitionsValueMust(TransitionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TransitionsType) ValueType(ctx context.Context) attr.Value {
	return TransitionsValue{}
}

var _ basetypes.ObjectValuable = TransitionsValue{}

type TransitionsValue struct {
	Label        basetypes.StringValue `tfsdk:"label"`
	TargetNodeId basetypes.StringValue `tfsdk:"target_node_id"`
	state        attr.ValueState
}

func (v TransitionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["label"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["target_node_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Label.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["label"] = val

		val, err = v.TargetNodeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["target_node_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TransitionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TransitionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TransitionsValue) String() string {
	return "TransitionsValue"
}

func (v TransitionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"label":          basetypes.StringType{},
		"target_node_id": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"label":          v.Label,
			"target_node_id": v.TargetNodeId,
		})

	return objVal, diags
}

func (v TransitionsValue) Equal(o attr.Value) bool {
	other, ok := o.(TransitionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Label.Equal(other.Label) {
		return false
	}

	if !v.TargetNodeId.Equal(other.TargetNodeId) {
		return false
	}

	return true
}

func (v TransitionsValue) Type(ctx context.Context) attr.Type {
	return TransitionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TransitionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"label":          basetypes.StringType{},
		"target_node_id": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ScheduleType{}

type ScheduleType struct {
	basetypes.ObjectType
}

func (t ScheduleType) Equal(o attr.Type) bool {
	other, ok := o.(ScheduleType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ScheduleType) String() string {
	return "ScheduleType"
}

func (t ScheduleType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	customFrequencyAttribute, ok := attributes["custom_frequency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_frequency is missing from object`)

		return nil, diags
	}

	customFrequencyVal, ok := customFrequencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_frequency expected to be basetypes.StringValue, was: %T`, customFrequencyAttribute))
	}

	customFrequencyAmountAttribute, ok := attributes["custom_frequency_amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_frequency_amount is missing from object`)

		return nil, diags
	}

	customFrequencyAmountVal, ok := customFrequencyAmountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_frequency_amount expected to be basetypes.Int64Value, was: %T`, customFrequencyAmountAttribute))
	}

	frequencyAttribute, ok := attributes["frequency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`frequency is missing from object`)

		return nil, diags
	}

	frequencyVal, ok := frequencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`frequency expected to be basetypes.StringValue, was: %T`, frequencyAttribute))
	}

	nextRunAttribute, ok := attributes["next_run"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`next_run is missing from object`)

		return nil, diags
	}

	nextRunVal, ok := nextRunAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`next_run expected to be basetypes.StringValue, was: %T`, nextRunAttribute))
	}

	scheduledAttribute, ok := attributes["scheduled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scheduled is missing from object`)

		return nil, diags
	}

	scheduledVal, ok := scheduledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scheduled expected to be basetypes.BoolValue, was: %T`, scheduledAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ScheduleValue{
		CustomFrequency:       customFrequencyVal,
		CustomFrequencyAmount: customFrequencyAmountVal,
		Frequency:             frequencyVal,
		NextRun:               nextRunVal,
		Scheduled:             scheduledVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewScheduleValueNull() ScheduleValue {
	return ScheduleValue{
		state: attr.ValueStateNull,
	}
}

func NewScheduleValueUnknown() ScheduleValue {
	return ScheduleValue{
		state: attr.ValueStateUnknown,
	}
}

func NewScheduleValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ScheduleValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ScheduleValue Attribute Value",
				"While creating a ScheduleValue value, a missing attribute value was detected. "+
					"A ScheduleValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScheduleValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ScheduleValue Attribute Type",
				"While creating a ScheduleValue value, an invalid attribute value was detected. "+
					"A ScheduleValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ScheduleValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ScheduleValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ScheduleValue Attribute Value",
				"While creating a ScheduleValue value, an extra attribute value was detected. "+
					"A ScheduleValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ScheduleValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewScheduleValueUnknown(), diags
	}

	customFrequencyAttribute, ok := attributes["custom_frequency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_frequency is missing from object`)

		return NewScheduleValueUnknown(), diags
	}

	customFrequencyVal, ok := customFrequencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_frequency expected to be basetypes.StringValue, was: %T`, customFrequencyAttribute))
	}

	customFrequencyAmountAttribute, ok := attributes["custom_frequency_amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`custom_frequency_amount is missing from object`)

		return NewScheduleValueUnknown(), diags
	}

	customFrequencyAmountVal, ok := customFrequencyAmountAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`custom_frequency_amount expected to be basetypes.Int64Value, was: %T`, customFrequencyAmountAttribute))
	}

	frequencyAttribute, ok := attributes["frequency"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`frequency is missing from object`)

		return NewScheduleValueUnknown(), diags
	}

	frequencyVal, ok := frequencyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`frequency expected to be basetypes.StringValue, was: %T`, frequencyAttribute))
	}

	nextRunAttribute, ok := attributes["next_run"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`next_run is missing from object`)

		return NewScheduleValueUnknown(), diags
	}

	nextRunVal, ok := nextRunAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`next_run expected to be basetypes.StringValue, was: %T`, nextRunAttribute))
	}

	scheduledAttribute, ok := attributes["scheduled"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`scheduled is missing from object`)

		return NewScheduleValueUnknown(), diags
	}

	scheduledVal, ok := scheduledAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`scheduled expected to be basetypes.BoolValue, was: %T`, scheduledAttribute))
	}

	if diags.HasError() {
		return NewScheduleValueUnknown(), diags
	}

	return ScheduleValue{
		CustomFrequency:       customFrequencyVal,
		CustomFrequencyAmount: customFrequencyAmountVal,
		Frequency:             frequencyVal,
		NextRun:               nextRunVal,
		Scheduled:             scheduledVal,
		state:                 attr.ValueStateKnown,
	}, diags
}

func NewScheduleValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ScheduleValue {
	object, diags := NewScheduleValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewScheduleValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ScheduleType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewScheduleValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewScheduleValueUnknown(), nil
	}

	if in.IsNull() {
		return NewScheduleValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewScheduleValueMust(ScheduleValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ScheduleType) ValueType(ctx context.Context) attr.Value {
	return ScheduleValue{}
}

var _ basetypes.ObjectValuable = ScheduleValue{}

type ScheduleValue struct {
	CustomFrequency       basetypes.StringValue `tfsdk:"custom_frequency"`
	CustomFrequencyAmount basetypes.Int64Value  `tfsdk:"custom_frequency_amount"`
	Frequency             basetypes.StringValue `tfsdk:"frequency"`
	NextRun               basetypes.StringValue `tfsdk:"next_run"`
	Scheduled             basetypes.BoolValue   `tfsdk:"scheduled"`
	state                 attr.ValueState
}

func (v ScheduleValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["custom_frequency"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["custom_frequency_amount"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["frequency"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["next_run"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["scheduled"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.CustomFrequency.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_frequency"] = val

		val, err = v.CustomFrequencyAmount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["custom_frequency_amount"] = val

		val, err = v.Frequency.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["frequency"] = val

		val, err = v.NextRun.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["next_run"] = val

		val, err = v.Scheduled.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["scheduled"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ScheduleValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ScheduleValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ScheduleValue) String() string {
	return "ScheduleValue"
}

func (v ScheduleValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"custom_frequency":        basetypes.StringType{},
		"custom_frequency_amount": basetypes.Int64Type{},
		"frequency":               basetypes.StringType{},
		"next_run":                basetypes.StringType{},
		"scheduled":               basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"custom_frequency":        v.CustomFrequency,
			"custom_frequency_amount": v.CustomFrequencyAmount,
			"frequency":               v.Frequency,
			"next_run":                v.NextRun,
			"scheduled":               v.Scheduled,
		})

	return objVal, diags
}

func (v ScheduleValue) Equal(o attr.Value) bool {
	other, ok := o.(ScheduleValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CustomFrequency.Equal(other.CustomFrequency) {
		return false
	}

	if !v.CustomFrequencyAmount.Equal(other.CustomFrequencyAmount) {
		return false
	}

	if !v.Frequency.Equal(other.Frequency) {
		return false
	}

	if !v.NextRun.Equal(other.NextRun) {
		return false
	}

	if !v.Scheduled.Equal(other.Scheduled) {
		return false
	}

	return true
}

func (v ScheduleValue) Type(ctx context.Context) attr.Type {
	return ScheduleType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ScheduleValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"custom_frequency":        basetypes.StringType{},
		"custom_frequency_amount": basetypes.Int64Type{},
		"frequency":               basetypes.StringType{},
		"next_run":                basetypes.StringType{},
		"scheduled":               basetypes.BoolType{},
	}
}
