// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ps4c_gcp_spend_cuds

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func Ps4cGcpSpendCudsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"billing_account_id": schema.StringAttribute{
				Required:            true,
				Description:         "GCP Billing Account ID (format `XXXXXX-XXXXXX-XXXXXX`; the account that owns the CUDs) that scopes the request.",
				MarkdownDescription: "GCP Billing Account ID (format `XXXXXX-XXXXXX-XXXXXX`; the account that owns the CUDs) that scopes the request.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^[A-Z0-9]{6}-[A-Z0-9]{6}-[A-Z0-9]{6}$"), ""),
				},
			},
			"gcp_service": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by PerfectScale for Commitments GCP product line. Omit to return all product lines.\nPossible values: `compute`, `cloud_sql`",
				MarkdownDescription: "Filter by PerfectScale for Commitments GCP product line. Omit to return all product lines.\nPossible values: `compute`, `cloud_sql`",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"compute",
						"cloud_sql",
					),
				},
			},
			"items": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"commitment_amount": schema.Float64Attribute{
							Computed:            true,
							Description:         "Hourly commitment amount.",
							MarkdownDescription: "Hourly commitment amount.",
						},
						"commitment_unit": schema.StringAttribute{
							Computed:            true,
							Description:         "Unit for `commitmentAmount`.",
							MarkdownDescription: "Unit for `commitmentAmount`.",
						},
						"consumption_model_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Provider-assigned ID of the pricing model this CUD's discount is applied through.",
							MarkdownDescription: "Provider-assigned ID of the pricing model this CUD's discount is applied through.",
						},
						"cud_id": schema.StringAttribute{
							Computed:            true,
							Description:         "CUD ID (provider-assigned).",
							MarkdownDescription: "CUD ID (provider-assigned).",
						},
						"cud_product_id": schema.StringAttribute{
							Computed:            true,
							Description:         "Provider-assigned ID of the product family (`cudProductName`) this CUD applies to.",
							MarkdownDescription: "Provider-assigned ID of the product family (`cudProductName`) this CUD applies to.",
						},
						"cud_product_name": schema.StringAttribute{
							Computed:            true,
							Description:         "Product family name (e.g. `Compute Flexible`, `Cloud Run`, `BigQuery`).",
							MarkdownDescription: "Product family name (e.g. `Compute Flexible`, `Cloud Run`, `BigQuery`).",
						},
						"cud_product_type": schema.StringAttribute{
							Computed:            true,
							Description:         "Raw provider CUD type label.",
							MarkdownDescription: "Raw provider CUD type label.",
						},
						"end_time": schema.StringAttribute{
							Computed:            true,
							Description:         "When the CUD term ends. Null when unknown.",
							MarkdownDescription: "When the CUD term ends. Null when unknown.",
						},
						"entitlement_scope": schema.StringAttribute{
							Computed:            true,
							Description:         "Provider resource path this CUD's discount is scoped to (typically the billing account).",
							MarkdownDescription: "Provider resource path this CUD's discount is scoped to (typically the billing account).",
						},
						"export_date": schema.StringAttribute{
							Computed:            true,
							Description:         "Timestamp of the BigQuery CUD export row this item was read from.",
							MarkdownDescription: "Timestamp of the BigQuery CUD export row this item was read from.",
						},
						"last_month_savings": schema.Float64Attribute{
							Computed:            true,
							Description:         "Realized savings in the last full calendar month.",
							MarkdownDescription: "Realized savings in the last full calendar month.",
						},
						"last_month_utilization": schema.Float64Attribute{
							Computed:            true,
							Description:         "Utilization in the last full calendar month, as a fraction from 0 to 1.",
							MarkdownDescription: "Utilization in the last full calendar month, as a fraction from 0 to 1.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "Provider commitment display name.",
							MarkdownDescription: "Provider commitment display name.",
						},
						"region": schema.StringAttribute{
							Computed:            true,
							Description:         "Region in raw provider form (`us-central1`), or `global` for cross-region spend CUDs. Not the `lower_snake_case` wire form used by the `region` query parameter.",
							MarkdownDescription: "Region in raw provider form (`us-central1`), or `global` for cross-region spend CUDs. Not the `lower_snake_case` wire form used by the `region` query parameter.",
						},
						"start_time": schema.StringAttribute{
							Computed:            true,
							Description:         "When the CUD term started. Null when unknown.",
							MarkdownDescription: "When the CUD term started. Null when unknown.",
						},
						"state": schema.StringAttribute{
							Computed:            true,
							Description:         "Raw provider commitment state.",
							MarkdownDescription: "Raw provider commitment state.",
						},
						"sub_type": schema.StringAttribute{
							Computed:            true,
							Description:         "Normalized coverage sub-type token (`UPPER_SNAKE`) identifying the product family within the product line.",
							MarkdownDescription: "Normalized coverage sub-type token (`UPPER_SNAKE`) identifying the product family within the product line.",
						},
						"term": schema.StringAttribute{
							Computed:            true,
							Description:         "Raw provider commitment term (ISO-8601 duration).",
							MarkdownDescription: "Raw provider commitment term (ISO-8601 duration).",
						},
					},
					CustomType: ItemsType{
						ObjectType: types.ObjectType{
							AttrTypes: ItemsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"max_results": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Maximum number of items to return. Server may return fewer. Defaults to 50; maximum 500.",
				MarkdownDescription: "Maximum number of items to return. Server may return fewer. Defaults to 50; maximum 500.",
				Validators: []validator.Int64{
					int64validator.Between(1, 500),
				},
			},
			"page_token": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Opaque cursor token returned by a previous list response. Omit to start from the beginning; an empty or absent token in a response means there are no more results. Do not parse it. A structurally invalid cursor returns `400` with code `pagination_token_invalid`; an expired cursor returns `400` with code `pagination_token_expired` — restart pagination from the beginning.",
				MarkdownDescription: "Opaque cursor token returned by a previous list response. Omit to start from the beginning; an empty or absent token in a response means there are no more results. Do not parse it. A structurally invalid cursor returns `400` with code `pagination_token_invalid`; an expired cursor returns `400` with code `pagination_token_expired` — restart pagination from the beginning.",
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by region scope, in `lower_snake_case` wire form (for example `us_east1`), or the\nliteral `global`. Requires `gcp_service`; a request with `region` but no `gcp_service`\nreturns `400` with code `gcp_service_required`. When both are omitted, all available\nregions for all available product lines are returned.\n\nThe value is format-validated, not checked against a closed region list: `compute` accepts\nonly `global`, `cloud_sql` accepts only concrete regions (never `global`), and a value that\nis malformed or incompatible with `gcp_service` returns `400` with code `validation_failed`.\nA well-formed, service-compatible region with no data returns `200` with an empty result.",
				MarkdownDescription: "Filter by region scope, in `lower_snake_case` wire form (for example `us_east1`), or the\nliteral `global`. Requires `gcp_service`; a request with `region` but no `gcp_service`\nreturns `400` with code `gcp_service_required`. When both are omitted, all available\nregions for all available product lines are returned.\n\nThe value is format-validated, not checked against a closed region list: `compute` accepts\nonly `global`, `cloud_sql` accepts only concrete regions (never `global`), and a value that\nis malformed or incompatible with `gcp_service` returns `400` with code `validation_failed`.\nA well-formed, service-compatible region with no data returns `200` with an empty result.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile("^(global|[a-z]+(_[a-z0-9]+)+)$"), ""),
				},
			},
			"row_count": schema.Int64Attribute{
				Computed:            true,
				Description:         "Best-effort count for the filtered result set. May be null or omitted for expensive counts.",
				MarkdownDescription: "Best-effort count for the filtered result set. May be null or omitted for expensive counts.",
			},
			"status": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Filter by CUD state. Omit to include all states.\nPossible values: `active`, `expired`, `creating`, `pending`, `cancelled`, `not_yet_active`",
				MarkdownDescription: "Filter by CUD state. Omit to include all states.\nPossible values: `active`, `expired`, `creating`, `pending`, `cancelled`, `not_yet_active`",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"active",
						"expired",
						"creating",
						"pending",
						"cancelled",
						"not_yet_active",
					),
				},
			},
		},
		Description:         "Evaluate current GCP commitments, plan and automate purchases, and optimize cloud costs with PerfectScale for Commitments.",
		MarkdownDescription: "Evaluate current GCP commitments, plan and automate purchases, and optimize cloud costs with PerfectScale for Commitments.",
	}
}

type Ps4cGcpSpendCudsModel struct {
	BillingAccountId types.String `tfsdk:"billing_account_id"`
	GcpService       types.String `tfsdk:"gcp_service"`
	Items            types.List   `tfsdk:"items"`
	MaxResults       types.Int64  `tfsdk:"max_results"`
	PageToken        types.String `tfsdk:"page_token"`
	Region           types.String `tfsdk:"region"`
	RowCount         types.Int64  `tfsdk:"row_count"`
	Status           types.String `tfsdk:"status"`
}

var _ basetypes.ObjectTypable = ItemsType{}

type ItemsType struct {
	basetypes.ObjectType
}

func (t ItemsType) Equal(o attr.Type) bool {
	other, ok := o.(ItemsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ItemsType) String() string {
	return "ItemsType"
}

func (t ItemsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if in.IsNull() {
		return NewItemsValueNull(), diags
	}

	if in.IsUnknown() {
		return NewItemsValueUnknown(), diags
	}

	attributes := in.Attributes()

	commitmentAmountAttribute, ok := attributes["commitment_amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_amount is missing from object`)

		return nil, diags
	}

	commitmentAmountVal, ok := commitmentAmountAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_amount expected to be basetypes.Float64Value, was: %T`, commitmentAmountAttribute))
	}

	commitmentUnitAttribute, ok := attributes["commitment_unit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_unit is missing from object`)

		return nil, diags
	}

	commitmentUnitVal, ok := commitmentUnitAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_unit expected to be basetypes.StringValue, was: %T`, commitmentUnitAttribute))
	}

	consumptionModelIdAttribute, ok := attributes["consumption_model_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`consumption_model_id is missing from object`)

		return nil, diags
	}

	consumptionModelIdVal, ok := consumptionModelIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`consumption_model_id expected to be basetypes.StringValue, was: %T`, consumptionModelIdAttribute))
	}

	cudIdAttribute, ok := attributes["cud_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_id is missing from object`)

		return nil, diags
	}

	cudIdVal, ok := cudIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_id expected to be basetypes.StringValue, was: %T`, cudIdAttribute))
	}

	cudProductIdAttribute, ok := attributes["cud_product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_product_id is missing from object`)

		return nil, diags
	}

	cudProductIdVal, ok := cudProductIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_product_id expected to be basetypes.StringValue, was: %T`, cudProductIdAttribute))
	}

	cudProductNameAttribute, ok := attributes["cud_product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_product_name is missing from object`)

		return nil, diags
	}

	cudProductNameVal, ok := cudProductNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_product_name expected to be basetypes.StringValue, was: %T`, cudProductNameAttribute))
	}

	cudProductTypeAttribute, ok := attributes["cud_product_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_product_type is missing from object`)

		return nil, diags
	}

	cudProductTypeVal, ok := cudProductTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_product_type expected to be basetypes.StringValue, was: %T`, cudProductTypeAttribute))
	}

	endTimeAttribute, ok := attributes["end_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_time is missing from object`)

		return nil, diags
	}

	endTimeVal, ok := endTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_time expected to be basetypes.StringValue, was: %T`, endTimeAttribute))
	}

	entitlementScopeAttribute, ok := attributes["entitlement_scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`entitlement_scope is missing from object`)

		return nil, diags
	}

	entitlementScopeVal, ok := entitlementScopeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`entitlement_scope expected to be basetypes.StringValue, was: %T`, entitlementScopeAttribute))
	}

	exportDateAttribute, ok := attributes["export_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`export_date is missing from object`)

		return nil, diags
	}

	exportDateVal, ok := exportDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`export_date expected to be basetypes.StringValue, was: %T`, exportDateAttribute))
	}

	lastMonthSavingsAttribute, ok := attributes["last_month_savings"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_month_savings is missing from object`)

		return nil, diags
	}

	lastMonthSavingsVal, ok := lastMonthSavingsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_month_savings expected to be basetypes.Float64Value, was: %T`, lastMonthSavingsAttribute))
	}

	lastMonthUtilizationAttribute, ok := attributes["last_month_utilization"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_month_utilization is missing from object`)

		return nil, diags
	}

	lastMonthUtilizationVal, ok := lastMonthUtilizationAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_month_utilization expected to be basetypes.Float64Value, was: %T`, lastMonthUtilizationAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return nil, diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	startTimeAttribute, ok := attributes["start_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time is missing from object`)

		return nil, diags
	}

	startTimeVal, ok := startTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time expected to be basetypes.StringValue, was: %T`, startTimeAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	subTypeAttribute, ok := attributes["sub_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sub_type is missing from object`)

		return nil, diags
	}

	subTypeVal, ok := subTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sub_type expected to be basetypes.StringValue, was: %T`, subTypeAttribute))
	}

	termAttribute, ok := attributes["term"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`term is missing from object`)

		return nil, diags
	}

	termVal, ok := termAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`term expected to be basetypes.StringValue, was: %T`, termAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ItemsValue{
		CommitmentAmount:     commitmentAmountVal,
		CommitmentUnit:       commitmentUnitVal,
		ConsumptionModelId:   consumptionModelIdVal,
		CudId:                cudIdVal,
		CudProductId:         cudProductIdVal,
		CudProductName:       cudProductNameVal,
		CudProductType:       cudProductTypeVal,
		EndTime:              endTimeVal,
		EntitlementScope:     entitlementScopeVal,
		ExportDate:           exportDateVal,
		LastMonthSavings:     lastMonthSavingsVal,
		LastMonthUtilization: lastMonthUtilizationVal,
		Name:                 nameVal,
		Region:               regionVal,
		StartTime:            startTimeVal,
		State:                stateVal,
		SubType:              subTypeVal,
		Term:                 termVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewItemsValueNull() ItemsValue {
	return ItemsValue{
		state: attr.ValueStateNull,
	}
}

func NewItemsValueUnknown() ItemsValue {
	return ItemsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewItemsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ItemsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ItemsValue Attribute Value",
				"While creating a ItemsValue value, a missing attribute value was detected. "+
					"A ItemsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ItemsValue Attribute Type",
				"While creating a ItemsValue value, an invalid attribute value was detected. "+
					"A ItemsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ItemsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ItemsValue Attribute Value",
				"While creating a ItemsValue value, an extra attribute value was detected. "+
					"A ItemsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ItemsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewItemsValueUnknown(), diags
	}

	commitmentAmountAttribute, ok := attributes["commitment_amount"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_amount is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	commitmentAmountVal, ok := commitmentAmountAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_amount expected to be basetypes.Float64Value, was: %T`, commitmentAmountAttribute))
	}

	commitmentUnitAttribute, ok := attributes["commitment_unit"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`commitment_unit is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	commitmentUnitVal, ok := commitmentUnitAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`commitment_unit expected to be basetypes.StringValue, was: %T`, commitmentUnitAttribute))
	}

	consumptionModelIdAttribute, ok := attributes["consumption_model_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`consumption_model_id is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	consumptionModelIdVal, ok := consumptionModelIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`consumption_model_id expected to be basetypes.StringValue, was: %T`, consumptionModelIdAttribute))
	}

	cudIdAttribute, ok := attributes["cud_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_id is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	cudIdVal, ok := cudIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_id expected to be basetypes.StringValue, was: %T`, cudIdAttribute))
	}

	cudProductIdAttribute, ok := attributes["cud_product_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_product_id is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	cudProductIdVal, ok := cudProductIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_product_id expected to be basetypes.StringValue, was: %T`, cudProductIdAttribute))
	}

	cudProductNameAttribute, ok := attributes["cud_product_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_product_name is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	cudProductNameVal, ok := cudProductNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_product_name expected to be basetypes.StringValue, was: %T`, cudProductNameAttribute))
	}

	cudProductTypeAttribute, ok := attributes["cud_product_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`cud_product_type is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	cudProductTypeVal, ok := cudProductTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`cud_product_type expected to be basetypes.StringValue, was: %T`, cudProductTypeAttribute))
	}

	endTimeAttribute, ok := attributes["end_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`end_time is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	endTimeVal, ok := endTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`end_time expected to be basetypes.StringValue, was: %T`, endTimeAttribute))
	}

	entitlementScopeAttribute, ok := attributes["entitlement_scope"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`entitlement_scope is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	entitlementScopeVal, ok := entitlementScopeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`entitlement_scope expected to be basetypes.StringValue, was: %T`, entitlementScopeAttribute))
	}

	exportDateAttribute, ok := attributes["export_date"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`export_date is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	exportDateVal, ok := exportDateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`export_date expected to be basetypes.StringValue, was: %T`, exportDateAttribute))
	}

	lastMonthSavingsAttribute, ok := attributes["last_month_savings"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_month_savings is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	lastMonthSavingsVal, ok := lastMonthSavingsAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_month_savings expected to be basetypes.Float64Value, was: %T`, lastMonthSavingsAttribute))
	}

	lastMonthUtilizationAttribute, ok := attributes["last_month_utilization"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`last_month_utilization is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	lastMonthUtilizationVal, ok := lastMonthUtilizationAttribute.(basetypes.Float64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`last_month_utilization expected to be basetypes.Float64Value, was: %T`, lastMonthUtilizationAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	regionAttribute, ok := attributes["region"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	regionVal, ok := regionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region expected to be basetypes.StringValue, was: %T`, regionAttribute))
	}

	startTimeAttribute, ok := attributes["start_time"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`start_time is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	startTimeVal, ok := startTimeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`start_time expected to be basetypes.StringValue, was: %T`, startTimeAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	subTypeAttribute, ok := attributes["sub_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sub_type is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	subTypeVal, ok := subTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sub_type expected to be basetypes.StringValue, was: %T`, subTypeAttribute))
	}

	termAttribute, ok := attributes["term"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`term is missing from object`)

		return NewItemsValueUnknown(), diags
	}

	termVal, ok := termAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`term expected to be basetypes.StringValue, was: %T`, termAttribute))
	}

	if diags.HasError() {
		return NewItemsValueUnknown(), diags
	}

	return ItemsValue{
		CommitmentAmount:     commitmentAmountVal,
		CommitmentUnit:       commitmentUnitVal,
		ConsumptionModelId:   consumptionModelIdVal,
		CudId:                cudIdVal,
		CudProductId:         cudProductIdVal,
		CudProductName:       cudProductNameVal,
		CudProductType:       cudProductTypeVal,
		EndTime:              endTimeVal,
		EntitlementScope:     entitlementScopeVal,
		ExportDate:           exportDateVal,
		LastMonthSavings:     lastMonthSavingsVal,
		LastMonthUtilization: lastMonthUtilizationVal,
		Name:                 nameVal,
		Region:               regionVal,
		StartTime:            startTimeVal,
		State:                stateVal,
		SubType:              subTypeVal,
		Term:                 termVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewItemsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ItemsValue {
	object, diags := NewItemsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewItemsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ItemsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewItemsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewItemsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewItemsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewItemsValueMust(ItemsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ItemsType) ValueType(ctx context.Context) attr.Value {
	return ItemsValue{}
}

var _ basetypes.ObjectValuable = ItemsValue{}

type ItemsValue struct {
	CommitmentAmount     basetypes.Float64Value `tfsdk:"commitment_amount"`
	CommitmentUnit       basetypes.StringValue  `tfsdk:"commitment_unit"`
	ConsumptionModelId   basetypes.StringValue  `tfsdk:"consumption_model_id"`
	CudId                basetypes.StringValue  `tfsdk:"cud_id"`
	CudProductId         basetypes.StringValue  `tfsdk:"cud_product_id"`
	CudProductName       basetypes.StringValue  `tfsdk:"cud_product_name"`
	CudProductType       basetypes.StringValue  `tfsdk:"cud_product_type"`
	EndTime              basetypes.StringValue  `tfsdk:"end_time"`
	EntitlementScope     basetypes.StringValue  `tfsdk:"entitlement_scope"`
	ExportDate           basetypes.StringValue  `tfsdk:"export_date"`
	LastMonthSavings     basetypes.Float64Value `tfsdk:"last_month_savings"`
	LastMonthUtilization basetypes.Float64Value `tfsdk:"last_month_utilization"`
	Name                 basetypes.StringValue  `tfsdk:"name"`
	Region               basetypes.StringValue  `tfsdk:"region"`
	StartTime            basetypes.StringValue  `tfsdk:"start_time"`
	State                basetypes.StringValue  `tfsdk:"state"`
	SubType              basetypes.StringValue  `tfsdk:"sub_type"`
	Term                 basetypes.StringValue  `tfsdk:"term"`
	state                attr.ValueState
}

func (v ItemsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 18)

	var val tftypes.Value
	var err error

	attrTypes["commitment_amount"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["commitment_unit"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["consumption_model_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cud_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cud_product_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cud_product_name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["cud_product_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["end_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["entitlement_scope"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["export_date"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["last_month_savings"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["last_month_utilization"] = basetypes.Float64Type{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["start_time"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["sub_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["term"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 18)

		val, err = v.CommitmentAmount.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["commitment_amount"] = val

		val, err = v.CommitmentUnit.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["commitment_unit"] = val

		val, err = v.ConsumptionModelId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["consumption_model_id"] = val

		val, err = v.CudId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cud_id"] = val

		val, err = v.CudProductId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cud_product_id"] = val

		val, err = v.CudProductName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cud_product_name"] = val

		val, err = v.CudProductType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["cud_product_type"] = val

		val, err = v.EndTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["end_time"] = val

		val, err = v.EntitlementScope.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["entitlement_scope"] = val

		val, err = v.ExportDate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["export_date"] = val

		val, err = v.LastMonthSavings.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_month_savings"] = val

		val, err = v.LastMonthUtilization.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["last_month_utilization"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Region.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region"] = val

		val, err = v.StartTime.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["start_time"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		val, err = v.SubType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["sub_type"] = val

		val, err = v.Term.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["term"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ItemsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ItemsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ItemsValue) String() string {
	return "ItemsValue"
}

func (v ItemsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"commitment_amount":      basetypes.Float64Type{},
		"commitment_unit":        basetypes.StringType{},
		"consumption_model_id":   basetypes.StringType{},
		"cud_id":                 basetypes.StringType{},
		"cud_product_id":         basetypes.StringType{},
		"cud_product_name":       basetypes.StringType{},
		"cud_product_type":       basetypes.StringType{},
		"end_time":               basetypes.StringType{},
		"entitlement_scope":      basetypes.StringType{},
		"export_date":            basetypes.StringType{},
		"last_month_savings":     basetypes.Float64Type{},
		"last_month_utilization": basetypes.Float64Type{},
		"name":                   basetypes.StringType{},
		"region":                 basetypes.StringType{},
		"start_time":             basetypes.StringType{},
		"state":                  basetypes.StringType{},
		"sub_type":               basetypes.StringType{},
		"term":                   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"commitment_amount":      v.CommitmentAmount,
			"commitment_unit":        v.CommitmentUnit,
			"consumption_model_id":   v.ConsumptionModelId,
			"cud_id":                 v.CudId,
			"cud_product_id":         v.CudProductId,
			"cud_product_name":       v.CudProductName,
			"cud_product_type":       v.CudProductType,
			"end_time":               v.EndTime,
			"entitlement_scope":      v.EntitlementScope,
			"export_date":            v.ExportDate,
			"last_month_savings":     v.LastMonthSavings,
			"last_month_utilization": v.LastMonthUtilization,
			"name":                   v.Name,
			"region":                 v.Region,
			"start_time":             v.StartTime,
			"state":                  v.State,
			"sub_type":               v.SubType,
			"term":                   v.Term,
		})

	return objVal, diags
}

func (v ItemsValue) Equal(o attr.Value) bool {
	other, ok := o.(ItemsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CommitmentAmount.Equal(other.CommitmentAmount) {
		return false
	}

	if !v.CommitmentUnit.Equal(other.CommitmentUnit) {
		return false
	}

	if !v.ConsumptionModelId.Equal(other.ConsumptionModelId) {
		return false
	}

	if !v.CudId.Equal(other.CudId) {
		return false
	}

	if !v.CudProductId.Equal(other.CudProductId) {
		return false
	}

	if !v.CudProductName.Equal(other.CudProductName) {
		return false
	}

	if !v.CudProductType.Equal(other.CudProductType) {
		return false
	}

	if !v.EndTime.Equal(other.EndTime) {
		return false
	}

	if !v.EntitlementScope.Equal(other.EntitlementScope) {
		return false
	}

	if !v.ExportDate.Equal(other.ExportDate) {
		return false
	}

	if !v.LastMonthSavings.Equal(other.LastMonthSavings) {
		return false
	}

	if !v.LastMonthUtilization.Equal(other.LastMonthUtilization) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Region.Equal(other.Region) {
		return false
	}

	if !v.StartTime.Equal(other.StartTime) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	if !v.SubType.Equal(other.SubType) {
		return false
	}

	if !v.Term.Equal(other.Term) {
		return false
	}

	return true
}

func (v ItemsValue) Type(ctx context.Context) attr.Type {
	return ItemsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ItemsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"commitment_amount":      basetypes.Float64Type{},
		"commitment_unit":        basetypes.StringType{},
		"consumption_model_id":   basetypes.StringType{},
		"cud_id":                 basetypes.StringType{},
		"cud_product_id":         basetypes.StringType{},
		"cud_product_name":       basetypes.StringType{},
		"cud_product_type":       basetypes.StringType{},
		"end_time":               basetypes.StringType{},
		"entitlement_scope":      basetypes.StringType{},
		"export_date":            basetypes.StringType{},
		"last_month_savings":     basetypes.Float64Type{},
		"last_month_utilization": basetypes.Float64Type{},
		"name":                   basetypes.StringType{},
		"region":                 basetypes.StringType{},
		"start_time":             basetypes.StringType{},
		"state":                  basetypes.StringType{},
		"sub_type":               basetypes.StringType{},
		"term":                   basetypes.StringType{},
	}
}
