// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_ava

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func AvaDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"answer": schema.StringAttribute{
				Computed:            true,
				Description:         "The Ava response text.",
				MarkdownDescription: "The Ava response text.",
			},
			"conversation_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The conversation ID. Present only for non-ephemeral requests. Can be used with the delete conversation endpoint.",
				MarkdownDescription: "The conversation ID. Present only for non-ephemeral requests. Can be used with the delete conversation endpoint.",
			},
		},
		Description:         "Interact with Ava, DoiT's AI-powered cloud assistant.",
		MarkdownDescription: "Interact with Ava, DoiT's AI-powered cloud assistant.",
	}
}

type AvaModel struct {
	Answer         types.String `tfsdk:"answer"`
	ConversationId types.String `tfsdk:"conversation_id"`
}
